### ISSUE TITLE
From help screen q quits program rather than returning to main screen

### ISSUE THREAD

**Issue by stuartthebruce** [zevv/duc#143] opened 2016-07-16 18:59 UTC
On Linix duc 1.4.1 exits when "q" is entered on the ui mode help screen, contrary to the help screen message,

   h:               show help. press 'q' to return to the main screen

**Comment by l8gravely** [comment] 2016-10-16 01:30
Just to let you know, I haven't found this to be a problem yet, but I did find a seg-fault in the 'duc ui' which has been fixed at the latest level.  Please clone the release and test it out some more, since we've put in a bunch of small changes since the last release.

**Comment by stuartthebruce** [comment] 2016-10-16 01:47
> On Oct 15, 2016, at 6:30 PM, John <notifications@github.com> wrote:
> 
> Just to let you know, I haven't found this to be a problem yet, but I did find a seg-fault in the 'duc ui' which has been fixed at the latest level. Please clone the release and test it out some more, since we’ve put in a bunch of small changes since the last release.

I can’t reproduce this problem with either an older build or a build from master today. Perhaps I had a sticky keyboard that bounced the “q” key.

However, the help screen indicates escape should also quit the help page, but that doesn’t seem to work for me on an SL7 machine,
   q, escape:       quit

Thanks.

--
Stuart Anderson  anderson@ligo.caltech.edu
http://www.ligo.caltech.edu/~anderson

**Comment by l8gravely** [comment] 2016-10-16 02:11
>>>>> "stuartthebruce" == stuartthebruce  <notifications@github.com> writes:

>> On Oct 15, 2016, at 6:30 PM, John <notifications@github.com> wrote:
>> 
>> Just to let you know, I haven't found this to be a problem yet, but I did
stuartthebruce> find a seg-fault in the 'duc ui' which has been fixed at the latest level.
stuartthebruce> Please clone the release and test it out some more, since we’ve put in a bunch
stuartthebruce> of small changes since the last release.

stuartthebruce> I can’t reproduce this problem with either an older
stuartthebruce> build or a build from master today. Perhaps I had a
stuartthebruce> sticky keyboard that bounced the “q” key.

I suspect it's how we handle reading from the keyboard.  We should be
emptying the buffer more aggresively when we go to do a command,
otherwise it might end up stacking keys and just doing wierd things.

stuartthebruce> However, the help screen indicates escape should also
stuartthebruce> quit the help page, but that doesn’t seem to work for
stuartthebruce> me on an SL7 machine, q, escape: quit

Yeah, that might also be related, or because I *think* it's piped
through less as a sub-process.  Haven't looked into the code in
detail.

The segfault was completely seperate issue that I ran into because of
my test script generates all kinds of wierd directory and file names,
and while going down them in the ui mode, I fell off the end of a
pointer.  So I don't think I found your problem, but I did find
another one!

I think we should close this one though, since it's not repeatable any
more.

John

**Comment by zevv** [comment] 2016-10-16 06:10
* On 2016-10-16 04:11:27 +0200, John wrote:
 
> I think we should close this one though, since it's not repeatable any
> more.

Ack

-- 
:wq
^X^Cy^K^X^C^C^C^C

**Closed** 2016-11-07 19:52 UTC
