### ISSUE TITLE
Coordinate problem when scrolling in cgi mode

### ISSUE THREAD

**Issue by stuartthebruce** [zevv/duc#145] opened 2016-07-16 19:10 UTC
For duc version 1.4.1 in cgi mode it the coordinates used by the tooltip and clicking on the map get out of sync when scrolling in the browser. I have observed this on OSX 10.11 using Firefox, Safari and Chrome. In particular, after scrolling a CGI page the tooltip display, and actually clicking, are referencing the part of the cgi map that would have been displayed at the location on my screen if I had not scrolled, i.e., they are unaware of scrolling.

**Comment by l8gravely** [comment] 2016-10-15 17:04
I think I know what the problem is, we need to add in something like this:

var BB=canvas.getBoundingClientRect();

var x=event.clientX-BB.left;
var y=event.clientY-BB.top;
  
I'll come up with a patch and push it to a new branch...

**Comment by l8gravely** [comment] 2016-10-15 22:27
I think this issue is already fixed in master.  Maybe it's time for 1.4.2 release?

**Comment by zevv** [comment] 2016-10-16 06:05
* On 2016-10-16 00:27:41 +0200, John wrote:
 
> I think this issue is already fixed in master.  Maybe it's time for 1.4.2 release?

I'd like to wait for John's CGI updates, which allow a custom header and
footer div in the html page. As soon as that is in I'm happy to spin a
new release.

-- 
:wq
^X^Cy^K^X^C^C^C^C

**Comment by l8gravely** [comment] 2016-10-20 19:35
I've got some new work pushed up.  See my various branches.  

css - css examples and doc updates
cgi-updates - some fixes and now support for the footer/header commands.

**Comment by zevv** [comment] 2016-10-25 18:21
Hi John,

> I've got some new work pushed up.  See my various branches.  
> 
> css - css examples and doc updates
> cgi-updates - some fixes and now support for the footer/header commands.

The CSS is looking just fine, just merge like it is.

I commented on the cgi a few days ago, but the mail probably got dropped
somewhere in the process. Here's my original comment:

  Looks pretty sane to me, this should allow seamless integration in
  almost any application.
               
  Two small things: Why not always print the div open and close tag for
  header and footer, and just include file content if the --header or
  --footer are given? Like
                 
    printf("  <div id=header>")
    print_div(opt_header))
    printf("  </div>")
               
  This way you can get rid of the DIV_HEADER and DIV_FOOTER constants and
  the extra argument of the print_div() function. (Which might in that
  case better be called something like 'include_file()')
               
  And please let's keep the default footer empty, I'm no big fan of tools
  showing clutter by default!

Thanks!

-- 
:wq
^X^Cy^K^X^C^C^C^C

**Comment by l8gravely** [comment] 2016-10-28 18:05
>>>>> "Ico" == Ico Doornekamp <notifications@github.com> writes:

Ico> Hi John,
>> I've got some new work pushed up. See my various branches.
>> 
>> css - css examples and doc updates
>> cgi-updates - some fixes and now support for the footer/header commands.

Ico> The CSS is looking just fine, just merge like it is.

Will do when I get a chance, it's been crazy here this week.

Ico> I commented on the cgi a few days ago, but the mail probably got dropped
Ico> somewhere in the process. Here's my original comment:

Ico> Looks pretty sane to me, this should allow seamless integration in
Ico> almost any application.

Ico> Two small things: Why not always print the div open and close tag for
Ico> header and footer, and just include file content if the --header or
Ico> --footer are given? Like

Ico> printf(" <div id=header>")
Ico> print_div(opt_header))
Ico> printf(" </div>")

I like this.  I thought about doing this way, but I decided not at the
time to give more control over the DIV, but thinking on it more, it's
a dumb idea.  

Ico> This way you can get rid of the DIV_HEADER and DIV_FOOTER
Ico> constants and the extra argument of the print_div()
Ico> function. (Which might in that case better be called something
Ico> like 'include_file()')

Yup.

Ico> And please let's keep the default footer empty, I'm no big fan of
Ico> tools showing clutter by default!

That's fine, I can live with that.  I'll try to do this update, but
not this weekend, camping with the scouts.  *grin*

**Comment by zevv** [comment] 2016-10-28 19:25
* On 2016-10-28 20:05:52 +0200, John wrote:
 
> That's fine, I can live with that.  I'll try to do this update, but
> not this weekend, camping with the scouts.  *grin*

No hurry. My turn for scout camp next week :)

-- 
:wq
^X^Cy^K^X^C^C^C^C

**Comment by l8gravely** [comment] 2016-10-28 20:28
Ico> * On 2016-10-28 20:05:52 +0200, John wrote:
>> That's fine, I can live with that. I'll try to do this update, but
>> not this weekend, camping with the scouts. *grin*

Ico> No hurry. My turn for scout camp next week :)

You have kids in scouts too?  Mine is going to the US National
Jamboree next year...

**Comment by stuartthebruce** [comment] 2016-11-22 04:51
I still see this problem with 1.4.2 running under Apache on SL7.

**Comment by stuartthebruce** [comment] 2016-12-31 00:31
I have lost track of this. In particular, is there any debugging information I can supply, or should I try a different version than 1.4.2? Many of the new users I point at nightly updates of their file usage get confused by this scrolling problem.

**Comment by l8gravely** [comment] 2016-12-31 00:42
>>>>> "stuartthebruce" == stuartthebruce  <notifications@github.com> writes:

stuartthebruce> I have lost track of this. In particular, is there any
stuartthebruce> debugging information I can supply, or should I try a
stuartthebruce> different version than 1.4.2? Many of the new users I
stuartthebruce> point at nightly updates of their file usage get
stuartthebruce> confused by this scrolling problem.

Hmm... my (dim) memory seems to say that we had fixed this with some
relative window hacks.  Basically noticing that the window had
scrolled from 0,0, and so we used an offset to figure things out
correctly.

Can you refresh our memory?  What OS and browser are the clients
using?

John

**Comment by zevv** [comment] 2016-12-31 17:02
Hi Stuart,

Quoting stuartthebruce (2016-12-31 17:34:57)

> Is it working for anyone else? Perhaps my wrapper script around
> “duc cgi” is messing up something?

I must admit I am able to reproduce straight away on Linux with Firefox.
For some reason I was under the impression that you were seeing a
MacOS-X specific issue and never looked into it myself.

I'll take a look at this shortly, but I have some social stuff to finish
first.


--
:wq
^X^Cy^K^X^C^C^C^C

**Comment by zevv** [comment] 2016-12-31 19:03
Quoting stuartthebruce (2016-12-31 17:34:57)

> I am seeing this problem with the web server running SL7+duc-1.4.2,
> and the client running OSX 10.12.2 with the latest version of
> Firefox, Safari or Chrome.

Last change of the year, 40e0bcde8720099cb7ec10f5b5023fd68b0a2d34 should
fix your problem. Sorry for not picking this up earlier!
 
--
:wq
^X^Cy^K^X^C^C^C^C

**Comment by l8gravely** [comment] 2016-12-31 20:24
>>>>> "Ico" == Ico Doornekamp <notifications@github.com> writes:

Ico> Quoting stuartthebruce (2016-12-31 17:34:57)
>> I am seeing this problem with the web server running SL7+duc-1.4.2,
>> and the client running OSX 10.12.2 with the latest version of
>> Firefox, Safari or Chrome.

Ico> Last change of the year, 40e0bcde8720099cb7ec10f5b5023fd68b0a2d34
Ico> should fix your problem. Sorry for not picking this up earlier!

Sweet!  Looks good here too.

**Comment by l8gravely** [comment] 2016-12-31 20:28
>>>>> "John" == John Stoffel <john@stoffel.org> writes:

>>>>> "Ico" == Ico Doornekamp <notifications@github.com> writes:
Ico> Quoting stuartthebruce (2016-12-31 17:34:57)
>>> I am seeing this problem with the web server running SL7+duc-1.4.2,
>>> and the client running OSX 10.12.2 with the latest version of
>>> Firefox, Safari or Chrome.

Ico> Last change of the year, 40e0bcde8720099cb7ec10f5b5023fd68b0a2d34
Ico> should fix your problem. Sorry for not picking this up earlier!

John> Sweet!  Looks good here too.  

I'd say tag it as 1.4.3 and release it too if you get this before you
party too hard.  :-)

**Comment by zevv** [comment] 2017-01-01 18:14
Closing this. @stuartthebruce: reopen if it is not fixed for you!

**Closed by zevv** 2017-01-01 18:14 UTC
