### ISSUE TITLE
Scan fails on active directories

### ISSUE THREAD

**Issue by spikebike** [zevv/duc#258] opened 2020-08-17 22:01 UTC
I built duc 1.4.4 from source been scanning directories with active files and it seems to kill the scan:

```
$ duc index -d /projects/foo/.duc-index/duc.db /projects/foo
/projects/foo done Error statting .rst: No such file or directory
```
Even on repeated attempts I can't finish a scan and it seems to stop the second it hits and error.

**Comment by l8gravely** [comment] 2020-08-17 23:54
Bill> I built duc 1.4.4 from source been scanning directories with
Bill> active files and it seems to kill the scan:

Bill> $ duc index -d /projects/foo/.duc-index/duc.db /projects/foo
Bill> /projects/foo done Error statting .rst: No such file or directory

Bill> Even on repeated attempts I can't finish a scan and it seems to
Bill> stop the second it hits and error.

Can you please run duc with the --debug switch and send me the output?
I've been using duc for quite a while and never run into this problem,
but I could see that if it hits a small window where the initial
readdir() gets a file, but then the file gets deleted before the
stat() call is done could be a problem.

Looking at the code, the only two places with this warning message are
in the src/libduc/index.c, and in neither place does the code exit.

Is that .rst file gone when duc stops?  Can you see that file with 'ls
-l'?

More details please.
John

**Comment by l8gravely** [comment] 2020-11-23 18:33
I've got some time off so I've been playing around trying to come up with a test case for this, but no luck so far.  It's surprisingly hard to get something that works like I want.  But I did find a tool called 'fdtree.sh' on github which sorta does what I want, but needs a random seed in it and then some way to update randomly.  

While running two of them against each other, and then running duc against the directory tree to see if I could cause a crash, I wasn't successful, but I did see a bunch of errors about statting a directory or file, so we're on the right track.  But no crashes so far using lmdb, so if you can also give us the output of:

duc --version

that would help.

**Comment by l8gravely** [comment] 2024-09-07 01:57
Closing this issue, since we can't replicate it and don't have a reproducer.  Also, v1.5.0-rc1 was released just this week, please try using that since there are various patches and updates.

**Closed by l8gravely** 2024-09-07 01:57 UTC
