### ISSUE TITLE
Dude, where is my database? - scanning a large folder yields non-usable database

### ISSUE THREAD

**Issue by guysoft** [zevv/duc#195] opened 2018-06-24 07:16 UTC
Hey,
So I wanted to use duc on our 10TB drive.
I ran it twice for about a week and got twice the output below, aka, it does not recognised anything indexed.
what can I do? 

The database at ``/srv/git/guy/duc.db`` is 3.2G, so its storing something, but I can't access it.

duc version: 1.3.3
options: cairo x11 ui tokyocabinet

Running on 
Ubuntu 15.10
```
root@website:/mnt# duc index --database /srv/git/guy/duc.db /srv/git/pro --verbose
Writing to database "/srv/git/guy/duc.db"
Indexed 669579957 files and 768915 directories, (8.5TB apparent, 10.3TB actual) in 4 days, 07 hours, 52 minutes, a
root@website:/srv# duc  info --database /srv/git/guy/duc.db  /srv/git/pro --verbose
Reading from database "/srv/git/guy/duc.db"
Date       Time       Files    Dirs    Size Path
root@website:/srv#
```

**Comment by zevv** [comment] 2018-06-24 18:51
I love the subject line :)

Quoting Guy Sheffer (2018-06-24 09:16:13)

> So I wanted to use duc on our 10TB drive.  I ran it twice for about a
> week and got twice the output below, aka, it does not recognised
> anything indexed.

Well, that's nasty, and I've not seen this before: if duc index finishes
without errors, the db is really supposed to be ok and available -
you're sure it did not terminate before finishing, for example by
accidentally closing the terminal 'duc index' was running in?

> what can I do? 

I would like to inspect your db file, but 3.2G is a bit of a hassle to
send, and I can imagine you might not like others to see your file
system. Could you check what's in the database with tokyocabinets
cmdline utility? If your run

  $ tcbmgr list duc.db | grep -v '[0-9]'

you should get a list of indexed paths, and two other keys starting with
'duc_', something like :

  /home/ico
  duc_db_version
  duc_index_reports

And running

  $ tcbmgr list .duc.db | wc -l

should show the number of keys in the database, which should probably be
several millions, in your case.


--
:wq
^X^Cy^K^X^C^C^C^C

**Comment by l8gravely** [comment] 2018-06-24 23:10
Guy> So I wanted to use duc on our 10TB drive.

We use it on multiple 10tb drives at my work, so I know it can handle
the load.  But you've indexed 669 million files at one shot, ouch!
That's a factor of 10 higher than I've ever done.

Can you run a test where you just index a much smaller section and see
what it says?

And what does 'df -i /srv/git/pro' and 'df -h /src/git/pro' return as
values?  

Guy> I ran it twice for about a week and got twice the output below,
Guy> aka, it does not recognised anything indexed.  what can I do?

Guy> The database at /srv/git/guy/duc.db is 3.2G, so its storing something, but I
Guy> can't access it.

Guy> duc version: 1.3.3
Guy> options: cairo x11 ui tokyocabinet

Guy> Running on
Guy> Ubuntu 15.10

Guy> root@website:/mnt# duc index --database /srv/git/guy/duc.db /srv/git/pro --verbose
Guy> Writing to database "/srv/git/guy/duc.db"
Guy> Indexed 669579957 files and 768915 directories, (8.5TB apparent, 10.3TB actual) in 4 days, 07 hours, 52 minutes, a
Guy> root@website:/srv# duc  info --database /srv/git/guy/duc.db  /srv/git/guy/duc.db --verbose
Guy> Reading from database "/srv/git/guy/duc.db"

Actually, I think I see your problem.  You want to do:

   duc  info --database /srv/git/guy/duc.db  /srv/git/guy/duc

You're listing the DB in the first AND second spots, which of course
won't be found.  But testing out duc on a smaller subset would be the
first step in my book.

John

**Comment by guysoft** [comment] 2018-06-25 10:33
@zevv I get:
```
tcbmgr list /srv/git/guy/duc.db | grep -v '[0-9]' 
tcbmgr: /srv/git/guy/duc.db: 6: invalid record header
```

If I run this on the new database I am indexing now, it does not exit so quickly.

@l8gravely ``df -i /srv/git/pro' and 'df -h /src/git/pro`` hangs for days. The minute I move to that folder just takes forever, that is why I am using duc in the first place.

Also in the meantime I rebuilt from master and running duc 1.4 to see if it will make a difference.

I can't run `` duc info --database /srv/git/guy/duc.db /srv/git/guy/duc`` because there version mismatches now. Also, I am indexing ``/srv/git/pro``, so why would i need to use ``/srv/git/guy/duc``? Is that a typo?

**Comment by l8gravely** [comment] 2018-06-25 16:41
Guy> @zevv I get:
Guy> tcbmgr list /srv/git/guy/duc.db | grep -v '[0-9]'
Guy> tcbmgr: /srv/git/guy/duc.db: 6: invalid record header

I suspect it's the size of your filesystem which is killing you.  When
was the last time you did an fsck of your data?  

Guy> If I run this on the new database I am indexing now, it does not exit so
Guy> quickly.

How big a directory are you indexing now?  Again, I'm just asking for
a small(ish) test area to see what's going on with duc.  I suspect duc
itself is fine, but your directory isn't.

Guy> @l8gravely df -i /srv/git/pro' and 'df -h /src/git/pro hangs for days. The
Guy> minute I move to that folder just takes forever, that is why I am using duc in
Guy> the first place.

Then you have bigger problems here.  What type of filesystem is this?
Can you provide more details?  Is it ext3?  ext4?  xfs?  glusterfs?

How many directories/files do you have at the top level of the system?
I know it's only 10tb in size, but when you say it has 669 million
files... then I suspect you're hitting major performance problems.

Actually, how does the CPU usage and memory usage look on this system?
I bet if you increased your memory, it would give you better
performance, because the metadata overhead of that filesystem is going
to be huge!

Guy> Also in the meantime I rebuilt from master and running duc 1.4 to
Guy> see if it will make a difference.

It might... but probably not.  Esp if it takes so long to just do a
'df -i' or 'df -h' on the filesystem.  

Guy> I can't run duc info --database /srv/git/guy/duc.db /srv/git/guy/duc because
Guy> there version mismatches now. Also, I am indexing /srv/git/pro, so why would i
Guy> need to use /srv/git/guy/duc? Is that a typo?

I was just thinking you had compiled duc into that directory.

**Comment by zevv** [comment] 2018-06-27 04:59
Quoting Guy Sheffer (2018-06-25 12:33:31)

> tcbmgr list /srv/git/guy/duc.db | grep -v '[0-9]' 
> tcbmgr: /srv/git/guy/duc.db: 6: invalid record header

That's nasty, this seems like a corrupted database - corrupteod at the
file level, that is. I have not seen this before myself, and I' not
quite sure how to proceed from here.

Duc has a bit of a problem with the database engine being used: we
support a handfull of different engines (sqlite, leveldb, berkeley,
tonkycabinet, kyotocabinet), and for good reasons we default to
tokyocabinet: it performs well in speed terms, but wins from all the
others for db file size because of good compression. The only problem is
that tokyocabinet is no longer supported by the original authords, so
any kind of bugs we run into can not be solved.

If your are comfortable with building Duc from source yourself and are
willing to spend some time testing, we could try to get you up and
running on a different database engine to see if that resolves your
issue. The problemy of course is that testing takes a long time each
run, so it might take a lot of your time.


--
:wq
^X^Cy^K^X^C^C^C^C

**Comment by guysoft** [comment] 2018-06-27 07:05
Hey, in answer to @l8gravely the filesystem is 10 1TB hard drives with ex4 on azure cloud. They are all stitched together using mergerfs. 
I am aware we have storage issues because we cache a lot of small files. The performance is fine, but stuff like reading the filesystem structure takes a long time. One of the reason I am running duc is to determine who is taking up all the storage.

@zevv If you want to give me instructions how to switch databases I could do that. I am pretty comfortable with building stuff. Great if it helps you too.

**Comment by l8gravely** [comment] 2018-06-27 20:39
>>>>> "Guy" == Guy Sheffer <notifications@github.com> writes:

Guy> Hey, in answer to @l8gravely the filesystem is 10 1TB hard drives with ex4 on
Guy> azure cloud. They are all stitched together using mergerfs.

That's probably the problem then.  Can you instead run duc against the
individual filesystems instead?  I still suspect the sheer number of
files is what's killing you.  

Guy> I am aware we have storage issues because we cache a lot of small
Guy> files. The performance is fine, but stuff like reading the
Guy> filesystem structure takes a long time. One of the reason I am
Guy> running duc is to determine who is taking up all the storage.

Guy> @zevv If you want to give me instructions how to switch databases
Guy> I could do that. I am pretty comfortable with building
Guy> stuff. Great if it helps you too.

Maybe what Ico and I need to do is try to spin up a test filesystem
with 120 million files or more and see how that works.  You might just
have found an edge case where tokyocabinet blows up because you're
using too many keys...

Is there any way you could run the duc index inside a gdb session
(while building with full debugging) to see if you can catch when the
error happens.

I've got the space and the filesystem capacity to try and spin up a
test system, but it will still take me time to deploy.

John

**Comment by l8gravely** [comment] 2018-06-27 20:57
>>>>> "Guy" == Guy Sheffer <notifications@github.com> writes:

Guy> Hey, in answer to @l8gravely the filesystem is 10 1TB hard drives with ex4 on
Guy> azure cloud. They are all stitched together using mergerfs.

This looks like an interesting tool, but I strongly suspect you're
running into an edge case in mergergs.  Have you talked with the devs
about how performance would be with such a large number of files?

Are you exporting this filesystem via NFS to other clients?  How much
memory do you have on the server you're running mergerfs on?

Can you run:

  tune2fs -l /path/to/device

for each of the 10 disks?  Or even find out which filesystem is the
most used by doing:

 df -i /path/to/device
 df -h /path/to/device

for each of the 10 1tb volumes.  That should at least get you some
*rough* numbers on how the load is split up.

Also, are you using the old INN trick of using multiple levels of
directories to break up things, so that you don't have a single
directory with 100,000 directories in it?  That's one of the big
issues with ext3/4 filesystems as I recall.  Performance degrades
rapidly in those cases.

John

**Comment by l8gravely** [comment] 2018-06-27 21:00
Hmm.... this might provide some useful info as well:

cd /path/to/mergerfs/vol
xattr -l .mergerfs

if you're willing to share it...

**Comment by zevv** [comment] 2018-06-27 21:52
> Maybe what Ico and I need to do is try to spin up a test filesystem
> with 120 million files or more and see how that works.  You might just
> have found an edge case where tokyocabinet blows up because you're
> using too many keys...

No use to go the long way, that's too much effort: I can just use the db
code and write out a zillion keys straight away. Currently running at
50M keys, db size 9.5G, still going strong.

> Is there any way you could run the duc index inside a gdb session
> (while building with full debugging) to see if you can catch when the
> error happens.

Using tcdbmgr also shows the error, so it's probably not Duc at fault
here.

--
:wq
^X^Cy^K^X^C^C^C^C

**Comment by guysoft** [comment] 2018-06-28 14:42
Hey,
So it finished, and 1.4 fixed the issue! Yay!
```
Indexed 677314479 files and 781193 directories, (8.5TB apparent, 10.3TB actual) in 4d, 6 hours, 33 minutes, and 53.17 seconds.
```

The database takes 3.4GB and not 3.2 GB as before. So perhaps it didn't crash on something right at the end.

Thanks for helping and giving an insight how to debug something like this, closing.

**Comment by l8gravely** [comment] 2018-06-28 14:48
Guy> So it finished, and 1.4 fixed the issue! Yay!

Good to know!

Guy> Indexed 677314479 files and 781193 directories, (8.5TB apparent,
Guy> 10.3TB actual) in 4d, 6 hours, 33 minutes, and 53.17 seconds.

Ah... it's 67 million, not 677 million files.  That's more believable
now.  

Guy> The database takes 3.4GB and not 3.2 GB as before. So perhaps it
Guy> didn't crash on something right at the end.

Hard to know.  Are you willing to re-try the latest 1.3 code branch? 

Guy> Thanks for helping and giving an insight how to debug something like this,
Guy> closing.

It was a fun thing to try and help with, and I've learned about
mergerfs, which is a good thing too.

John

**Comment by guysoft** [comment] 2018-07-10 22:20
If tou

**Closed** 2018-07-10 22:20 UTC

**Comment by guysoft** [comment] 2018-07-10 22:22
If you really want I could test, but give me a good reason to run this for 4 days. Hiw does the outcome help you?

**Comment by zevv** [comment] 2018-07-11 05:52
Quoting Guy Sheffer (2018-07-11 00:22:04)
> If you really want I could test, but give me a good reason to run this for 4 days. Hiw does the outcome help you?

Well, given the problem is solved with the latest version of Duc, I see
no need for further testing. @John: is there anything else you could
learn from such a test?

--
:wq
^X^Cy^K^X^C^C^C^C

**Comment by l8gravely** [comment] 2018-07-11 19:35
>>>>> "Ico" == Ico Doornekamp <notifications@github.com> writes:

Ico> Quoting Guy Sheffer (2018-07-11 00:22:04)
>> If you really want I could test, but give me a good reason to run this for 4
Ico> days. Hiw does the outcome help you?

Ico> Well, given the problem is solved with the latest version of Duc,
Ico> I see no need for further testing. @John: is there anything else
Ico> you could learn from such a test?

Not really. When I thought you had 660 million files, the shere scale
was interesting, but then when you showed it was just 66 million
files, I felt that I do stuff just like that scale without problems,
and that the newer version fixing the issue was good enough.

John

**Comment by guysoft** [comment] 2018-07-11 20:29
It was 600million.

**Comment by zevv** [comment] 2018-07-11 20:30
> [...] just 66 million files [...]

:)

**Comment by l8gravely** [comment] 2018-07-12 02:34
Then that is an interesting test case.   Again, can you post the output of ‘df-I /mnt/path ‘ please?  That’s -i of course, stupid hard to edit emails on this phone.

**Comment by guysoft** [comment] 2018-07-12 08:44
Yep, 689427907 innodes
1:2:3:4:5:6:7:8:9:10:11:12:13 871563264 689427907 182135357   80% /srv/git
