### ISSUE TITLE
indexed directories must be present at analysis?

### ISSUE THREAD

**Issue by daduke** [zevv/duc#71] opened 2015-04-20 07:11 UTC
Hi Ico,

as mentioned back in January, we use duc to visualize group share usage on our file servers.  We generate the duc database files on the file servers and then copy them to the 'visualization web server' where people can view their CGI graphs. So far so good, working great with the duc version I compiled back in January. Now I pulled the latest commits and recompiled, and I have the following problem: directly on the file servers it still works great. On the web server however (duc DBs copied over), `duc info` shows the root directory of the database, but then `duc ls` doesn't give any output. I used strace to try and debug the problem and saw this:

`lstat("/export", 0x7fff1e1a0000)        = -1 ENOENT (No such file or directory)`

`/export/groupdata/` is the top level directory of the shares on our file servers. It doesn't exist on the web server though, and apparently some commit between January and last Friday now requires indexed directories to be present at the time of analyzing the database? Is this intended behavior? If not necessary, it'd be great if analysis could run irrespective of directories existing at run time.

thanks,
-Christian

**Comment by zevv** [comment] 2015-04-20 07:34
* On 2015-04-20 09:11:29 +0200, Christian Herzog wrote:
 
> > apparently some commit between January and last Friday now requires
> indexed directories to be present at the time of analyzing the
> database? Is this intended behavior? If not necessary, it'd be great
> if analysis could run irrespective of directories existing at run
> time.

That's indeed not as it should be, I'll investigate and report back.

-- 
:wq
^X^Cy^K^X^C^C^C^C

**Comment by zevv** [comment] 2015-04-20 07:47
Hi Christian,

Could you please pull and try again? The problem is in the function duc
uses for normalizing paths. This function should convert relative paths
into absolute paths so everything in the db is always stored from the
same root. The problem was that this function does not resolve symbolic
links, so the same directory can end up in the database more then once
under the same name. To fix this I changed this function to use the C
library 'realpath()' function, but I was not aware that this function
assumes a path is available on the local filesystem.

The latest version changes back to the old  behaviour which should fix
your use case. It does *not* normalize symlinks at indexing however,
which is something I would still like to fix in the future.

* On 2015-04-20 09:33:53 +0200, Ico Doornekamp wrote:
 
> * On 2015-04-20 09:11:29 +0200, Christian Herzog wrote:
>  
> > > apparently some commit between January and last Friday now requires
> > indexed directories to be present at the time of analyzing the
> > database? Is this intended behavior? If not necessary, it'd be great
> > if analysis could run irrespective of directories existing at run
> > time.
> 
> That's indeed not as it should be, I'll investigate and report back.
> 

-- 
:wq
^X^Cy^K^X^C^C^C^C

**Comment by daduke** [comment] 2015-04-20 07:55
Hi Ico,

thanks for the fast response. Unfortunately the latest pull doesn't build for me:

`cmd-ui.c: In function ‘do_dir’:  
cmd-ui.c:77:3: warning: implicit declaration of function ‘attrset’ [-Wimplicit-function-declaration]
cmd-ui.c:77:11: error: ‘A_REVERSE’ undeclared (first use in this function)
cmd-ui.c:77:11: note: each undeclared identifier is reported only once for each function it appears in  
cmd-ui.c:78:3: warning: implicit declaration of function ‘mvhline’ [-Wimplicit-function-declaration]  
cmd-ui.c:79:3: warning: implicit declaration of function ‘mvprintw’ [-Wimplicit-function-declaration] 
cmd-ui.c:123:6: warning: implicit declaration of function ‘printw’ [-Wimplicit-function-declaration] 
cmd-ui.c:130:5: warning: implicit declaration of function ‘attron’ [-Wimplicit-function-declaration]  
cmd-ui.c:130:25: error: ‘A_BOLD’ undeclared (first use in this function)  
cmd-ui.c:132:5: warning: implicit declaration of function ‘attroff’ [-Wimplicit-function-declaration]  
cmd-ui.c:146:13: error: ‘A_DIM’ undeclared (first use in this function)
cmd-ui.c:157:3: warning: implicit declaration of function ‘getch’ [-Wimplicit-function-declaration]  
cmd-ui.c:160:9: error: ‘KEY_UP’ undeclared (first use in this function)  
cmd-ui.c:161:9: error: ‘KEY_DOWN’ undeclared (first use in this function)  
cmd-ui.c:162:9: error: ‘KEY_PPAGE’ undeclared (first use in this function)  
cmd-ui.c:163:9: error: ‘KEY_NPAGE’ undeclared (first use in this function)
cmd-ui.c:164:9: error: ‘KEY_RESIZE’ undeclared (first use in this function)  
cmd-ui.c:164:4: warning: implicit declaration of function ‘getmaxyx’ [-Wimplicit-function-declaration]  
cmd-ui.c:164:30: error: ‘stdscr’ undeclared (first use in this function)  
cmd-ui.c:174:9: error: ‘KEY_BACKSPACE’ undeclared (first use in this function)  
cmd-ui.c:175:9: error: ‘KEY_LEFT’ undeclared (first use in this function)
cmd-ui.c:187:9: error: ‘KEY_RIGHT’ undeclared (first use in this function)  
cmd-ui.c: In function ‘bye’:  
cmd-ui.c:210:2: warning: implicit declaration of function ‘endwin’ [-Wimplicit-function-declaration]  
cmd-ui.c: In function ‘ui_main’:  
cmd-ui.c:230:2: warning: implicit declaration of function ‘initscr’ [-Wimplicit-function-declaration]
cmd-ui.c:232:2: warning: implicit declaration of function ‘cbreak’ [-Wimplicit-function-declaration]  
cmd-ui.c:233:2: warning: implicit declaration of function ‘noecho’ [-Wimplicit-function-declaration]  
cmd-ui.c:234:2: warning: implicit declaration of function ‘nonl’ [-Wimplicit-function-declaration]  
cmd-ui.c:235:2: warning: implicit declaration of function ‘keypad’ [-Wimplicit-function-declaration]  
cmd-ui.c:235:9: error: ‘stdscr’ undeclared (first use in this function)
cmd-ui.c:237:2: warning: implicit declaration of function ‘curs_set’ [-Wimplicit-function-declaration]  
cmd-ui.c:238:2: warning: implicit declaration of function ‘start_color’ [-Wimplicit-function-declaration]  
cmd-ui.c:239:2: warning: implicit declaration of function ‘use_default_colors’ [-Wimplicit-function-declaration]  
make[2]: *** [cmd-ui.o] Error 1  
`

halp?

thanks,
-Christian

**Comment by zevv** [comment] 2015-04-20 08:02
* On 2015-04-20 09:55:10 +0200, Christian Herzog wrote:
 
> Hi Ico,
> 
> thanks for the fast response. Unfortunately the latest pull doesn't build for me:

Hm, that seems to be the new ncurses user interface which does not build
for you. I think my dependency checking in autoconf is flawed, autoconf
is still voodoo to me.

Do you have the ncurses library and headers installed? On debian/ubuntu
thats

# apt-get install libncurses5-dev



> `cmd-ui.c: In function ‘do_dir’:  
> cmd-ui.c:77:3: warning: implicit declaration of function ‘attrset’ [-Wimplicit-function-declaration]
> cmd-ui.c:77:11: error: ‘A_REVERSE’ undeclared (first use in this function)
> cmd-ui.c:77:11: note: each undeclared identifier is reported only once for each function it appears in  
> cmd-ui.c:78:3: warning: implicit declaration of function ‘mvhline’ [-Wimplicit-function-declaration]  
> cmd-ui.c:79:3: warning: implicit declaration of function ‘mvprintw’ [-Wimplicit-function-declaration] 
> cmd-ui.c:123:6: warning: implicit declaration of function ‘printw’ [-Wimplicit-function-declaration] 
> cmd-ui.c:130:5: warning: implicit declaration of function ‘attron’ [-Wimplicit-function-declaration]  
> cmd-ui.c:130:25: error: ‘A_BOLD’ undeclared (first use in this function)  
> cmd-ui.c:132:5: warning: implicit declaration of function ‘attroff’ [-Wimplicit-function-declaration]  
> cmd-ui.c:146:13: error: ‘A_DIM’ undeclared (first use in this function)
> cmd-ui.c:157:3: warning: implicit declaration of function ‘getch’ [-Wimplicit-function-declaration]  
> cmd-ui.c:160:9: error: ‘KEY_UP’ undeclared (first use in this function)  
> cmd-ui.c:161:9: error: ‘KEY_DOWN’ undeclared (first use in this function)  
> cmd-ui.c:162:9: error: ‘KEY_PPAGE’ undeclared (first use in this function)  
> cmd-ui.c:163:9: error: ‘KEY_NPAGE’ undeclared (first use in this function)
> cmd-ui.c:164:9: error: ‘KEY_RESIZE’ undeclared (first use in this function)  
> cmd-ui.c:164:4: warning: implicit declaration of function ‘getmaxyx’ [-Wimplicit-function-declaration]  
> cmd-ui.c:164:30: error: ‘stdscr’ undeclared (first use in this function)  
> cmd-ui.c:174:9: error: ‘KEY_BACKSPACE’ undeclared (first use in this function)  
> cmd-ui.c:175:9: error: ‘KEY_LEFT’ undeclared (first use in this function)
> cmd-ui.c:187:9: error: ‘KEY_RIGHT’ undeclared (first use in this function)  
> cmd-ui.c: In function ‘bye’:  
> cmd-ui.c:210:2: warning: implicit declaration of function ‘endwin’ [-Wimplicit-function-declaration]  
> cmd-ui.c: In function ‘ui_main’:  
> cmd-ui.c:230:2: warning: implicit declaration of function ‘initscr’ [-Wimplicit-function-declaration]
> cmd-ui.c:232:2: warning: implicit declaration of function ‘cbreak’ [-Wimplicit-function-declaration]  
> cmd-ui.c:233:2: warning: implicit declaration of function ‘noecho’ [-Wimplicit-function-declaration]  
> cmd-ui.c:234:2: warning: implicit declaration of function ‘nonl’ [-Wimplicit-function-declaration]  
> cmd-ui.c:235:2: warning: implicit declaration of function ‘keypad’ [-Wimplicit-function-declaration]  
> cmd-ui.c:235:9: error: ‘stdscr’ undeclared (first use in this function)
> cmd-ui.c:237:2: warning: implicit declaration of function ‘curs_set’ [-Wimplicit-function-declaration]  
> cmd-ui.c:238:2: warning: implicit declaration of function ‘start_color’ [-Wimplicit-function-declaration]  
> cmd-ui.c:239:2: warning: implicit declaration of function ‘use_default_colors’ [-Wimplicit-function-declaration]  
> make[2]: *** [cmd-ui.o] Error 1  
> `
> 
> halp?
> 
> thanks,
> -Christian
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/zevv/duc/issues/71#issuecomment-94385513

-- 
:wq
^X^Cy^K^X^C^C^C^C

**Comment by zevv** [comment] 2015-04-20 08:50
The code has also been fixed not to try to compile the ncurses user
interface if libncurses was not detected at ./configure time.

* On 2015-04-20 09:55:10 +0200, Christian Herzog wrote:
 
> Hi Ico,
> 
> thanks for the fast response. Unfortunately the latest pull doesn't build for me:
> 
> `cmd-ui.c: In function ‘do_dir’:  
> cmd-ui.c:77:3: warning: implicit declaration of function ‘attrset’ [-Wimplicit-function-declaration]
> cmd-ui.c:77:11: error: ‘A_REVERSE’ undeclared (first use in this function)
> cmd-ui.c:77:11: note: each undeclared identifier is reported only once for each function it appears in  
> cmd-ui.c:78:3: warning: implicit declaration of function ‘mvhline’ [-Wimplicit-function-declaration]  
> cmd-ui.c:79:3: warning: implicit declaration of function ‘mvprintw’ [-Wimplicit-function-declaration] 
> cmd-ui.c:123:6: warning: implicit declaration of function ‘printw’ [-Wimplicit-function-declaration] 
> cmd-ui.c:130:5: warning: implicit declaration of function ‘attron’ [-Wimplicit-function-declaration]  
> cmd-ui.c:130:25: error: ‘A_BOLD’ undeclared (first use in this function)  
> cmd-ui.c:132:5: warning: implicit declaration of function ‘attroff’ [-Wimplicit-function-declaration]  
> cmd-ui.c:146:13: error: ‘A_DIM’ undeclared (first use in this function)
> cmd-ui.c:157:3: warning: implicit declaration of function ‘getch’ [-Wimplicit-function-declaration]  
> cmd-ui.c:160:9: error: ‘KEY_UP’ undeclared (first use in this function)  
> cmd-ui.c:161:9: error: ‘KEY_DOWN’ undeclared (first use in this function)  
> cmd-ui.c:162:9: error: ‘KEY_PPAGE’ undeclared (first use in this function)  
> cmd-ui.c:163:9: error: ‘KEY_NPAGE’ undeclared (first use in this function)
> cmd-ui.c:164:9: error: ‘KEY_RESIZE’ undeclared (first use in this function)  
> cmd-ui.c:164:4: warning: implicit declaration of function ‘getmaxyx’ [-Wimplicit-function-declaration]  
> cmd-ui.c:164:30: error: ‘stdscr’ undeclared (first use in this function)  
> cmd-ui.c:174:9: error: ‘KEY_BACKSPACE’ undeclared (first use in this function)  
> cmd-ui.c:175:9: error: ‘KEY_LEFT’ undeclared (first use in this function)
> cmd-ui.c:187:9: error: ‘KEY_RIGHT’ undeclared (first use in this function)  
> cmd-ui.c: In function ‘bye’:  
> cmd-ui.c:210:2: warning: implicit declaration of function ‘endwin’ [-Wimplicit-function-declaration]  
> cmd-ui.c: In function ‘ui_main’:  
> cmd-ui.c:230:2: warning: implicit declaration of function ‘initscr’ [-Wimplicit-function-declaration]
> cmd-ui.c:232:2: warning: implicit declaration of function ‘cbreak’ [-Wimplicit-function-declaration]  
> cmd-ui.c:233:2: warning: implicit declaration of function ‘noecho’ [-Wimplicit-function-declaration]  
> cmd-ui.c:234:2: warning: implicit declaration of function ‘nonl’ [-Wimplicit-function-declaration]  
> cmd-ui.c:235:2: warning: implicit declaration of function ‘keypad’ [-Wimplicit-function-declaration]  
> cmd-ui.c:235:9: error: ‘stdscr’ undeclared (first use in this function)
> cmd-ui.c:237:2: warning: implicit declaration of function ‘curs_set’ [-Wimplicit-function-declaration]  
> cmd-ui.c:238:2: warning: implicit declaration of function ‘start_color’ [-Wimplicit-function-declaration]  
> cmd-ui.c:239:2: warning: implicit declaration of function ‘use_default_colors’ [-Wimplicit-function-declaration]  
> make[2]: *** [cmd-ui.o] Error 1  
> `
> 
> halp?
> 
> thanks,
> -Christian
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/zevv/duc/issues/71#issuecomment-94385513

-- 
:wq
^X^Cy^K^X^C^C^C^C

**Comment by daduke** [comment] 2015-04-20 08:53
Hi Ico,

ok ncurses did the trick, but now I have a different problem: Database version mismatch. I pulled on both machines, recompiled and rebuilt the database, but the web server wouldn't read the file server DB.. stay tuned...

-Christian

**Comment by zevv** [comment] 2015-04-20 09:35
* On 2015-04-20 10:53:25 +0200, Christian Herzog wrote:
 
> ok ncurses did the trick, but now I have a different problem: Database
> version mismatch. I pulled on both machines, recompiled and rebuilt
> the database, but the web server wouldn't read the file server DB..
> stay tuned...

That is caused by a change in the internal database format; I did some
optimization to reduce the database size, but this breaks db
compatibility between versions. The error message could be a bit more
descriptive, telling the user to throw away the database and run 'duc
index' again.

(I'm currently not doing anything special to preserve database
compatibility between versions; if needed I just change the database
format and increase the version number.)

-- 
:wq
^X^Cy^K^X^C^C^C^C

**Comment by daduke** [comment] 2015-04-20 10:00
ok clean install from scratch on both hosts. Good news: duc working again, including cgi. Bad news: directories show up as files:
![duc](https://cloud.githubusercontent.com/assets/818170/7227892/a87eed28-e754-11e4-9af6-141b652d0f4d.png)
this directory only contains subfolders, no files.

thanks for your help,
-Christian

**Comment by zevv** [comment] 2015-04-20 10:09
* On 2015-04-20 12:00:07 +0200, Christian Herzog wrote:
 
> ok clean install from scratch on both hosts. Good news: duc working
> again, including cgi. Bad news: directories show up as files:
> ![duc](https://cloud.githubusercontent.com/assets/818170/7227892/a87eed28-e754-11e4-9af6-141b652d0f4d.png)
> this directory only contains subfolders, no files.

Well, that's funny. You're not using the --hide-files flag on 'duc
index', are you?

-- 
:wq
^X^Cy^K^X^C^C^C^C

**Comment by daduke** [comment] 2015-04-20 10:10
yes I am, but these are directories, and it was working fine with the January version...

**Comment by zevv** [comment] 2015-04-20 10:23
* On 2015-04-20 12:10:34 +0200, Christian Herzog wrote:
 
> yes I am, but these are directories, and it was working fine with the January version...

Something fishy is going on here. The code says:

 if((req->flags & DUC_INDEX_HIDE_FILE_NAMES) && e->d_type != DT_DIR) { 
    name = "<FILE>";
 }

meaning: if the --hide-files flag is given, and the directory entry is
not a directory, change it's name into "<FILE>". So something must be
wrong with the e->d_type not being DT_DIR when it should be.

I'm not able to reproduce here unfortunately. I hope you have some time
to help me figure this out.

Could you try to add this line in lib/index.c, underneat the comment
'Hide file names', around line 239:

	printf("%s %d %d\n", e->d_name, e->d_type, DT_DIR);

and run 'duc index' on this directory you just sent a screenshot of?

-- 
:wq
^X^Cy^K^X^C^C^C^C

**Comment by daduke** [comment] 2015-04-20 10:25
ok I'll reindex w/o `--hide-files` and we'll take it from there.

**Comment by daduke** [comment] 2015-04-20 10:37
same binary, just w/o `--hide-files` -> looks better, but clicking on any folder doesn't descend?
![duc](https://cloud.githubusercontent.com/assets/818170/7228504/08f2597e-e75a-11e4-99ba-80ed520a588c.png)

**Comment by zevv** [comment] 2015-04-20 10:38
* On 2015-04-20 12:25:50 +0200, Christian Herzog wrote:
 
> ok I'll reindex w/o `--hide-files` and we'll take it from there.

Do you see the same behaviour if you index on your other host (the
machine you display on)? If not, what is the architecture, OS and
version of the host you are indexing on?

-- 
:wq
^X^Cy^K^X^C^C^C^C

**Comment by daduke** [comment] 2015-04-20 10:50
very interesting. Indexing locally on the web server works, even with `--hide-files` enabled. Also clicking into directories descends.

file server: Ubuntu 14.04.2 LTS

web server: Debian GNU/Linux 7.8 (wheezy)

both running the latest duc commit. Only difference: on the web server, duc was built locally, while for Ubuntu I built it on a dev machine and used our deployment tool to distribute binaries + lib (no compiler on file servers and stuff).

**Comment by zevv** [comment] 2015-04-20 11:04
* On 2015-04-20 12:50:29 +0200, Christian Herzog wrote:
 
> both running the latest duc commit. Only difference: on the web
> server, duc was built locally, while for Ubuntu I built it on a dev
> machine and used our deployment tool to distribute binaries + lib (no
> compiler on file servers and stuff).

That's funny, that would mean that the value of DT_DIR is not constant
between libcs on these machines, I have no other simple explanation. But
then again, it is hard to understand how indexing would even be
possible, since during traversion the DT_DIR constant is also used.

I'm afraid I need some more time to think about this one...

-- 
:wq
^X^Cy^K^X^C^C^C^C

**Comment by daduke** [comment] 2015-04-20 11:21
it's getting weirder by the minute..

2 indexing jobs on the file server:
`/opt/duc/bin/duc index -d /tmp/duc.isg --hide-files --maxdepth 10 /export/windeploy/winisg` -> duc.isg shows `<FILE>`
`/opt/duc/bin/duc index -d /tmp/duc.usr --hide-files --maxdepth 10 /usr` -> duc.usr shows directory names

do you want the DB files?

**Comment by zevv** [comment] 2015-04-20 11:44
* On 2015-04-20 13:21:52 +0200, Christian Herzog wrote:
 
> it's getting weirder by the minute..
> 
> 2 indexing jobs on the file server:
> `/opt/duc/bin/duc index -d /tmp/duc.isg --hide-files --maxdepth 10 /export/windeploy/winisg` -> duc.isg shows `<FILE>`
> `/opt/duc/bin/duc index -d /tmp/duc.usr --hide-files --maxdepth 10 /usr` -> duc.usr shows directory names

> do you want the DB files?

Not yet, we know the content is broken because the indexing process got
confused by the readdir() results.

I'm actually interested in the exact results returned by the readdir()
library call during indexing, I feel that the output might not be
reliable on some file systems. 

What file system type is /export on your server? Is it a local disk or
maybe NFS/iscsi netapp or something like that?

Could you maybe run an index run with the printf() added I mailed
earlier today to see what d_type gets returned?

-- 
:wq
^X^Cy^K^X^C^C^C^C

**Comment by daduke** [comment] 2015-04-20 11:56
`/usr` is `/dev/mapper/vg0-root on / type ext4 (rw,errors=remount-ro)` on a local disk while `/export` is `/dev/mapper/vgWinDeploy-lvWisg on /export/windeploy/winisg type xfs (rw,inode64,_netdev)` on iSCSI block devices

I'd be happy to add a printf() but I'm not sure what you're referring to (no earlier printf in this conversation..)

**Comment by zevv** [comment] 2015-04-20 12:17
* On 2015-04-20 13:56:16 +0200, Christian Herzog wrote:
 
> `/usr` is `/dev/mapper/vg0-root on / type ext4 (rw,errors=remount-ro)` on a
> local disk while `/export` is `/dev/mapper/vgWinDeploy-lvWisg on
> /export/windeploy/winisg type xfs (rw,inode64,_netdev)` on iSCSI block devices

Ok, I think we're closing in on the issue here: it seems that the d_type field
returned by readdir() is not guaranteed to return sane results on all file
systems, so my assumptions were wrong here. The man page says about the d_type
field:

 "Currently,  only  some  filesystems (among them: Btrfs, ext2, ext3, and ext4)
 have full support for returning the file type in d_type.  All applications must
 properly handle a return of DT_UNKNOWN."

I just changed the code where the file type is determined to use the
lstat() result instead of the d_type field. Please pull and try again!


 

-- 
:wq
^X^Cy^K^X^C^C^C^C

**Comment by daduke** [comment] 2015-04-20 12:49
brilliant! everything seems to be working again.

thanks a lot for your help,
-Christian

**Comment by zevv** [comment] 2015-04-20 13:01
* On 2015-04-20 14:49:38 +0200, Christian Herzog wrote:
 
> brilliant! everything seems to be working again.

Great news!

One more think: I'd like to rename the option --hide-files to
--hide-file-names, which better resembles the actual functionality of
this flag. Any problems for you with that?

-- 
:wq
^X^Cy^K^X^C^C^C^C

**Comment by zevv** [comment] 2015-04-20 15:16
Closing, resolved

**Closed by zevv** 2015-04-20 15:16 UTC

**Comment by l8gravely** [comment] 2015-04-21 13:07
>>>>> "zevv" == zevv  <notifications@github.com> writes:

zevv> * On 2015-04-20 09:55:10 +0200, Christian Herzog wrote:
>> Hi Ico,
>> 
>> thanks for the fast response. Unfortunately the latest pull doesn't build for me:

zevv> Hm, that seems to be the new ncurses user interface which does
zevv> not build for you. I think my dependency checking in autoconf is
zevv> flawed, autoconf is still voodoo to me.

Send me the full details and I'll try to poke at it for you.  I'm
traveling for work and busy, but this might just be what I need to
wind down my day.

Christian, can you give me more details about your system?  I've got
Debian/Mint at home and RHEL/Centos at work, so I can probably find a
fix.

John


zevv> Do you have the ncurses library and headers installed? On debian/ubuntu
zevv> thats

zevv> # apt-get install libncurses5-dev

>> `cmd-ui.c: In function ‘do_dir’:
>> cmd-ui.c:77:3: warning: implicit declaration of function ‘attrset’ [-Wimplicit-function-declaration]
>> cmd-ui.c:77:11: error: ‘A_REVERSE’ undeclared (first use in this function)
>> cmd-ui.c:77:11: note: each undeclared identifier is reported only once for each function it appears in
>> cmd-ui.c:78:3: warning: implicit declaration of function ‘mvhline’ [-Wimplicit-function-declaration]
>> cmd-ui.c:79:3: warning: implicit declaration of function ‘mvprintw’ [-Wimplicit-function-declaration]
>> cmd-ui.c:123:6: warning: implicit declaration of function ‘printw’ [-Wimplicit-function-declaration]
>> cmd-ui.c:130:5: warning: implicit declaration of function ‘attron’ [-Wimplicit-function-declaration]
>> cmd-ui.c:130:25: error: ‘A_BOLD’ undeclared (first use in this function)
>> cmd-ui.c:132:5: warning: implicit declaration of function ‘attroff’ [-Wimplicit-function-declaration]
>> cmd-ui.c:146:13: error: ‘A_DIM’ undeclared (first use in this function)
>> cmd-ui.c:157:3: warning: implicit declaration of function ‘getch’ [-Wimplicit-function-declaration]
>> cmd-ui.c:160:9: error: ‘KEY_UP’ undeclared (first use in this function)
>> cmd-ui.c:161:9: error: ‘KEY_DOWN’ undeclared (first use in this function)
>> cmd-ui.c:162:9: error: ‘KEY_PPAGE’ undeclared (first use in this function)
>> cmd-ui.c:163:9: error: ‘KEY_NPAGE’ undeclared (first use in this function)
>> cmd-ui.c:164:9: error: ‘KEY_RESIZE’ undeclared (first use in this function)
>> cmd-ui.c:164:4: warning: implicit declaration of function ‘getmaxyx’ [-Wimplicit-function-declaration]
>> cmd-ui.c:164:30: error: ‘stdscr’ undeclared (first use in this function)
>> cmd-ui.c:174:9: error: ‘KEY_BACKSPACE’ undeclared (first use in this function)
>> cmd-ui.c:175:9: error: ‘KEY_LEFT’ undeclared (first use in this function)
>> cmd-ui.c:187:9: error: ‘KEY_RIGHT’ undeclared (first use in this function)
>> cmd-ui.c: In function ‘bye’:
>> cmd-ui.c:210:2: warning: implicit declaration of function ‘endwin’ [-Wimplicit-function-declaration]
>> cmd-ui.c: In function ‘ui_main’:
>> cmd-ui.c:230:2: warning: implicit declaration of function ‘initscr’ [-Wimplicit-function-declaration]
>> cmd-ui.c:232:2: warning: implicit declaration of function ‘cbreak’ [-Wimplicit-function-declaration]
>> cmd-ui.c:233:2: warning: implicit declaration of function ‘noecho’ [-Wimplicit-function-declaration]
>> cmd-ui.c:234:2: warning: implicit declaration of function ‘nonl’ [-Wimplicit-function-declaration]
>> cmd-ui.c:235:2: warning: implicit declaration of function ‘keypad’ [-Wimplicit-function-declaration]
>> cmd-ui.c:235:9: error: ‘stdscr’ undeclared (first use in this function)
>> cmd-ui.c:237:2: warning: implicit declaration of function ‘curs_set’ [-Wimplicit-function-declaration]
>> cmd-ui.c:238:2: warning: implicit declaration of function ‘start_color’ [-Wimplicit-function-declaration]
>> cmd-ui.c:239:2: warning: implicit declaration of function ‘use_default_colors’ [-Wimplicit-function-declaration]
>> make[2]: *** [cmd-ui.o] Error 1
>> `
>> 
>> halp?
>> 
>> thanks,
>> -Christian
>> 
>> ---
>> Reply to this email directly or view it on GitHub:
>> https://github.com/zevv/duc/issues/71#issuecomment-94385513

zevv> --
zevv> :wq
zevv> ^X^Cy^K^X^C^C^C^C

zevv> —
zevv> Reply to this email directly or view it on GitHub.*

**Comment by l8gravely** [comment] 2015-04-21 13:13
>>>>> "zevv" == zevv  <notifications@github.com> writes:

zevv> * On 2015-04-20 14:49:38 +0200, Christian Herzog wrote:
>> brilliant! everything seems to be working again.

zevv> Great news!

zevv> One more think: I'd like to rename the option --hide-files to
zevv> --hide-file-names, which better resembles the actual
zevv> functionality of this flag. Any problems for you with that?

Short version alias?  I like the name chane myself... makes it more
clear.  For the short form... maybe umm... -N  as an option?  

And boy, the duc.1 man page needs alot of work.  I'll see about doing
that when I get a chance.  

John

**Comment by daduke** [comment] 2015-04-21 13:25
hey John,

I'm afraid I'm not exactly sure I understand your previous two comments - the quoting looks pretty confusing. Would you still like me to provide details even though the issue has been resolved?

best,
-Christian

**Comment by zevv** [comment] 2015-04-21 13:37
* On 2015-04-21 15:13:06 +0200, John wrote:
 
> Short version alias?  I like the name chane myself... makes it more
> clear.  For the short form... maybe umm... -N  as an option?  

I'm relucant to give out short options for every long option; after some
time your run out of options that make sense and you end up with a
confusing lot. Let's reserve the short options for things that really
matter, and leave the ones in that are already assigned for backwards
compatiblity, but be careful with assigning new shortopts.

> And boy, the duc.1 man page needs alot of work.  I'll see about doing
> that when I get a chance.  

Yeah, that's a lot of work to keep up to date. Ideally I would love it
if both the man pages and the --help output come from the same source,
so there's only one single place to write down the documentation. Not
sure what would be the right approach, though.

-- 
:wq
^X^Cy^K^X^C^C^C^C

**Comment by l8gravely** [comment] 2015-04-21 15:55
Christian> I'm afraid I'm not exactly sure I understand your previous
Christian> two comments - the quoting looks pretty confusing. Would
Christian> you still like me to provide details even though the issue
Christian> has been resolved?

Sorry, just trying to help out with the autoconfigure problem
detecting the properly ncurses libs are installed or not.  So if you
could send me the following details, that would help:

1. which distro are you using?
2. Can you send me the broken config.log output?

I'm the one who setup the autoconfigure stuff, so I'll try to fix it.

John

**Comment by zevv** [comment] 2015-04-21 16:01
Hi John,

The problem was (kind of) fixed already, autoconf properly detects if
ncurses is installed. If not found, duc will be compiled without the
ncurses user interface.

-- 
:wq
^X^Cy^K^X^C^C^C^C

**Comment by l8gravely** [comment] 2015-04-21 17:16
zevv> The problem was (kind of) fixed already, autoconf properly
zevv> detects if ncurses is installed. If not found, duc will be
zevv> compiled without the ncurses user interface.

Do we want to offer an option maybe, so that if it's not detected, we
compile it out but also mention what needs to be installed?
Dunno... wanted to poke at it by $WORK is keeping me busy.
