### ISSUE TITLE
duc gui:  extended arguments from commandline

### ISSUE THREAD

**Issue by nonsns** [zevv/duc#67] opened 2015-04-09 21:03 UTC
**feature request**

it would be useful to have a way to pass all graphical options (eg, fuzzying, maxlevels, etc.) to the gui
* either pass options from an environment variable as in DUCGUI="-some option --someother option"
* or from the command line 

PS.
I love the tool; I was actually using philesight some time ago, but I have to say duc improvements in usuability, speed and index size are impressive: keep on rocking!

**Comment by zevv** [comment] 2015-04-12 19:52
Duplicate of #49;

**Closed by zevv** 2015-04-12 19:52 UTC

**Comment by nonsns** [comment] 2015-04-16 07:33
ops, sorry 

I didn't realize that there was another semantically equivalent, but largely more confortable, option (i.e., file config of #49)

**Comment by zevv** [comment] 2015-04-16 07:35
* On 2015-04-16 09:33:18 +0200, Dario Rossi wrote:
 
> ops, sorry 
> 
> I didn't realize that there was another semantically equivalent, but
> largely more confortable, option (i.e., file config of #49)

There was not at the time you created the issue, this feature was added
just recently :)

-- 
:wq
^X^Cy^K^X^C^C^C^C
