### ISSUE TITLE
Problem building duc-1.2 on Solaris 11.2 x86_64

### ISSUE THREAD

**Issue by stuartthebruce** [zevv/duc#90] opened 2015-05-13 05:23 UTC
An attempt to build duc-1.2 on Solaris 11.2 x86_64 fails first at,

In file included from src/libduc/private.h:4:0,
                 from src/libduc/buffer.c:11:
src/libduc/duc.h:79:12: error: ‘NAME_MAX’ undeclared here (not in a function)

Replacing NAME_MAX with MAXNAMLEN as suggested here,
https://www.midnight-commander.org/ticket/1943
then gets to,

gcc -DHAVE_CONFIG_H -I.    -D_REENTRANT -D_POSIX_PTHREAD_SEMANTICS -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng12   -D_REENTRANT -D_PTHREADS -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include   -D_REENTRANT -D_PTHREADS -D_POSIX_PTHREAD_SEMANTICS -I/usr/include/pango-1.0 -I/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng12 -I/opt/csw/include    -Isrc/libduc -Isrc/libduc-graph -g -O2 -MT src/libduc/db.o -MD -MP -MF $depbase.Tpo -c -o src/libduc/db.o src/libduc/db.c &&\
mv -f $depbase.Tpo $depbase.Po
src/libduc/db.c: In function ‘db_write_dir’:
src/libduc/db.c:40:19: error: ‘DT_DIR’ undeclared (first use in this function)
src/libduc/db.c:40:19: note: each undeclared identifier is reported only once for each function it appears in
src/libduc/db.c: In function ‘db_read_dir’:
src/libduc/db.c:102:14: error: ‘DT_DIR’ undeclared (first use in this function)
gmake[1]: *** [src/libduc/db.o] Error 1

I haven't tried a fix for that yet, but would something like the following be appropriate?
http://notmuchmail.org/pipermail/notmuch/2009/001002.html

P.S. I am actually much more interested in getting this to work on Solaris than OS X since we have a number of large Solaris filesystems that I am currently indexing with duc over NFS to Linux clients that I would rather index directly on the fileservers if possible. FWIW, I believe I got an earlier release to compile a few months ago without running into DT_DIR.

Thanks

**Comment by zevv** [comment] 2015-05-13 06:30
* On 2015-05-13 07:24:00 +0200, stuartthebruce wrote:
 
> An attempt to build duc-1.2 on Solaris 11.2 x86_64 fails first at,

I assume you are trying to build the cgi-tooltip branch instead of
release 1.2? Because there is no NAME_MAX in the master branch.

> Replacing NAME_MAX with MAXNAMLEN as suggested here,
> https://www.midnight-commander.org/ticket/1943

Works for me, using MAXNAMLEN instead of NAME_MAX.

> src/libduc/db.c:40:19: error: ‘DT_DIR’ undeclared (first use in this function)

I happened to have replaced all the dirent DT_* constants by a enum
DUC_FILE_TYPE_ in the master branch yesterday. I just merged master into
the cgi-tooltip branch, if you could pull to latest and retry?

-- 
:wq
^X^Cy^K^X^C^C^C^C

**Comment by stuartthebruce** [comment] 2015-05-13 16:39
> On May 12, 2015, at 11:30 PM, Ico Doornekamp <notifications@github.com> wrote:
> 
> * On 2015-05-13 07:24:00 +0200, stuartthebruce wrote:
> 
> > An attempt to build duc-1.2 on Solaris 11.2 x86_64 fails first at,
> 
> I assume you are trying to build the cgi-tooltip branch instead of
> release 1.2? Because there is no NAME_MAX in the master branch.

Doh…this was indeed an attempt to build cgi-tooltip.

> 
> > Replacing NAME_MAX with MAXNAMLEN as suggested here,
> > https://www.midnight-commander.org/ticket/1943
> 
> Works for me, using MAXNAMLEN instead of NAME_MAX.
> 
> > src/libduc/db.c:40:19: error: ‘DT_DIR’ undeclared (first use in this function)
> 
> I happened to have replaced all the dirent DT_* constants by a enum
> DUC_FILE_TYPE_ in the master branch yesterday. I just merged master into
> the cgi-tooltip branch, if you could pull to latest and retry?

It gets past that now and has a problem with ncurses. In particular,
./configure passes its ncurses test (perhaps only looking for the library
and not the include file?) as reported here,

  configuration summary:

   - Package version: duc 1.2
   - Prefix: /usr/local
   - Database backend: tokyocabinet
   - GUI (X11) support: yes
   - UI (ncurses) support: yes
   - Graph drawing support: yes

however compiling fails at,

gcc -DHAVE_CONFIG_H -I.    -D_REENTRANT -D_POSIX_PTHREAD_SEMANTICS -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng12   -D_REENTRANT -D_PTHREADS -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include   -D_REENTRANT -D_PTHREADS -D_POSIX_PTHREAD_SEMANTICS -I/usr/include/pango-1.0 -I/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng12 -I/opt/csw/include    -Isrc/libduc -Isrc/libduc-graph -g -O2 -MT src/duc/cmd-ui.o -MD -MP -MF $depbase.Tpo -c -o src/duc/cmd-ui.o src/duc/cmd-ui.c &&\
mv -f $depbase.Tpo $depbase.Po
src/duc/cmd-ui.c:20:21: fatal error: ncurses.h: No such file or directory

This is due to ncurses.h living in the directory /usr/include/ncurses.
If I manually add -I/usr/include/ncurses for that compile command it
then builds a duc executable.

However, for duc to find an OpenCSW install of tokyocabinet (since that
package is not bundled in Solaris 11) I have to add the following,

env PKG_CONFIG_PATH=/opt/csw/lib/pkgconfig ./configure

This results in properly adding -L/opt/csw/lib to the final link
command, but it does not add -R/opt/csw/lib, so the final duc
executable does not know how to automatically find libtokyocabinet.so.9.
Rather than setting LD_LIBRARY_PATH at execute time I manaully
re-rran the final libtool command with -R/opt/csw/lib and that fixes
that problem.

A few simple tests are working,

# uname -sri
SunOS 5.11 i86pc

# pkg list entire
NAME (PUBLISHER)                                  VERSION                    IFO
entire (solaris)                                  0.5.11-0.175.2.9.0.5.0     i--

# ./duc --version
duc version 1.2

# ./duc index -x -v -p /
Writing to database "/root/.duc.db"
Skipping net: not crossing file system boundaries
Skipping devices: not crossing file system boundariestories
Skipping proc: not crossing file system boundariesirectories
Skipping SRU-11.2.3.5.0: not crossing file system boundaries
Skipping SRU-11.2.4.6.0: not crossing file system boundaries
Skipping SRU-11.2.5.5.0: not crossing file system boundaries
Skipping SRU-11.2.8.5.0: not crossing file system boundaries
Skipping SRU-11.2.6.4.0: not crossing file system boundaries
Skipping SRU-11.2.8.4.0: not crossing file system boundaries
Skipping SRU-11.2.3.4.1: not crossing file system boundaries
Skipping SRU-11.2.9.5.0: not crossing file system boundaries
Skipping full: not crossing file system boundaries
Skipping SRU-11.2.7.4.0: not crossing file system boundaries
Skipping contract: not crossing file system boundariestories
Skipping volatile: not crossing file system boundaries
Skipping object: not crossing file system boundaries
Skipping zones: not crossing file system boundaries
Skipping rpool: not crossing file system boundaries
Skipping usr1: not crossing file system boundariesdirectories
Skipping tmp: not crossing file system boundaries
Skipping export: not crossing file system boundaries
Skipping imports: not crossing file system boundaries
Skipping devscratch: not crossing file system boundaries
Skipping dev: not crossing file system boundaries
Skipping var: not crossing file system boundaries
Indexed 106580 files and 5077 directories, (3.8GB apparent, 2.4GB actual) in 2.187090 secs.

# ./duc info
Date       Time       Files    Dirs    Size Path
2015-05-13 09:30:08  106.6K    5.1K    2.4G /

However, I will upload a gui image that I am confused by.

Thanks.

--
Stuart Anderson  anderson@ligo.caltech.edu
http://www.ligo.caltech.edu/~anderson

**Comment by stuartthebruce** [comment] 2015-05-13 16:41
Here is a an image of duc gui on a Solaris test machine that confuses me as to why only a small fraction of the 360degree is being used?

![pastedgraphic-10](https://cloud.githubusercontent.com/assets/12385914/7615675/0626d5d8-f954-11e4-88bb-c5cb9470dc7d.png)

**Comment by stuartthebruce** [comment] 2015-05-13 18:21
Unfortunately, with the default database backend choice of tokyocabinet I am unable to use database files created under Solaris on a Linux box, or vice versa, even when sticking to the same x86_64 architectures, e.g.,

Solaris reading a Linux generated file,

# ./duc info -d ../anderson.duc 
Date       Time       Files    Dirs    Size Path
1969-12-31 16:00:00       0       0       0 /mnt/qfs1/anderson

or Linux reading a Solaris generated file,

# /usr/local/bin/duc info
Date       Time       Files    Dirs    Size Path
#

Is there an expectation that this should work?

**Comment by zevv** [comment] 2015-05-13 20:03
* On 2015-05-13 20:21:46 +0200, stuartthebruce wrote:
 
> Unfortunately, with the default database backend choice of tokyocabinet I am unable to use database files created under Solaris on a Linux box, or vice versa, even when sticking to the same x86_64 architectures, e.g.,
> 
> Solaris reading a Linux generated file,
> 
> # ./duc info -d ../anderson.duc 
> Date       Time       Files    Dirs    Size Path
> 1969-12-31 16:00:00       0       0       0 /mnt/qfs1/anderson
> 
> or Linux reading a Solaris generated file,
> 
> # /usr/local/bin/duc info
> Date       Time       Files    Dirs    Size Path
> #
> 
> Is there an expectation that this should work?

At this time portability between different architectures is not
guaranteed, but changing this would not be too problematic. 

Most information in the database is written in a int-size-independent
and endian-independent format, except for the reports, which are simply
written as binary structs into the database. I'll look into this to see
what the impact would be to change this.

Apart from the contents of the database, we'll have to figure out if
tokyocabinet databases as such re portable at all.
 

-- 
:wq
^X^Cy^K^X^C^C^C^C

**Comment by stuartthebruce** [comment] 2015-05-13 20:10
> On May 13, 2015, at 1:03 PM, Ico Doornekamp <notifications@github.com> wrote:
> 
> * On 2015-05-13 20:21:46 +0200, stuartthebruce wrote:
> 
> > Unfortunately, with the default database backend choice of tokyocabinet I am unable to use database files created under Solaris on a Linux box, or vice versa, even when sticking to the same x86_64 architectures, e.g.,
> > 
> > Solaris reading a Linux generated file,
> > 
> > # ./duc info -d ../anderson.duc 
> > Date Time Files Dirs Size Path
> > 1969-12-31 16:00:00 0 0 0 /mnt/qfs1/anderson
> > 
> > or Linux reading a Solaris generated file,
> > 
> > # /usr/local/bin/duc info
> > Date Time Files Dirs Size Path
> > #
> > 
> > Is there an expectation that this should work?
> 
> At this time portability between different architectures is not
> guaranteed, but changing this would not be too problematic. 
> 
> Most information in the database is written in a int-size-independent
> and endian-independent format, except for the reports, which are simply
> written as binary structs into the database. I'll look into this to see
> what the impact would be to change this.

That would be great. Note, in this case both machines are 64-bit Intel HW.

> 
> Apart from the contents of the database, we'll have to figure out if
> tokyocabinet databases as such re portable at all.

Understood. If the duc reports work I will help test tokyocabinet.

P.S. I did try sqlite under Linux for a performance comparison with
tokyocabinet and found no significant wall clock difference, however,
the sqlite database files where quite a bit larger than tokyocabinet,
up to 2x the size if I recall correctly.

Thanks.

--
Stuart Anderson  anderson@ligo.caltech.edu
http://www.ligo.caltech.edu/~anderson

**Comment by zevv** [comment] 2015-05-13 20:38
* On 2015-05-13 22:10:47 +0200, stuartthebruce wrote:
 
> > Most information in the database is written in a int-size-independent
> > and endian-independent format, except for the reports, which are simply
> > written as binary structs into the database. I'll look into this to see
> > what the impact would be to change this.

Please check out the portable-db branch and see if that solves your
issue.

> That would be great. Note, in this case both machines are 64-bit Intel HW.

Hm, that's unexpected. If that's the case I'm not sure if your issue is
fixed by this update.
 
> P.S. I did try sqlite under Linux for a performance comparison with
> tokyocabinet and found no significant wall clock difference, however,
> the sqlite database files where quite a bit larger than tokyocabinet,
> up to 2x the size if I recall correctly.

Indeed; I've tested a lot of different db engines, and chose
tokyocabinet because of its small database size with decent performance.
IIRC it was only significantly outperformed by leveldb, but I do not
like the added complexity of the leveldb database structure (directory
with files)

I had code lying around for berkeley and gdbm as well, if I still have
those around I can add them to the project as well because both are very
portable and common.

-- 
:wq
^X^Cy^K^X^C^C^C^C

**Comment by stuartthebruce** [comment] 2015-05-13 23:59
The portable-db branch is a significant step forward.

The info command now works on Solaris to read both a Solaris and Linux generated file,

# ./duc info -d solaris.duc 
Date       Time       Files    Dirs    Size Path
2015-05-13 16:41:15  106.8K    5.1K    2.4G /
# ./duc info -d linux.duc 
Date       Time       Files    Dirs    Size Path
2015-05-13 16:41:27  294.9K   29.6K   14.0G /

However, Linux is not able to read the Solaris file,

# ./duc info -d solaris.duc
Date       Time       Files    Dirs    Size Path
[root@ldas-pcdev2 duc-portable-db]# ./duc info -d linux.duc 
Date       Time       Files    Dirs    Size Path
2015-05-13 16:41:27  294.9K   29.6K   14.0G /

Note, both machines compiled the same copy of index.c, i.e., 

# md5sum src/libduc/index.c
70d4cb3cbb95ecbf2c3ae1117e5a9429  src/libduc/index.c

Nonetheless, Linux is able to generate a gui display of the Solaris file, and provide the full image, as opposed to the partial image posted previously when the Solaris file is viewed on Solaris,

![pastedgraphic-11](https://cloud.githubusercontent.com/assets/12385914/7623561/9373af10-f990-11e4-944a-b441ee5cf38c.png)

Perhaps related to the different gui graphs the ui command the Solaris system down not show the sort the entries by size, whereas the Linux build does, i.e.,

Solaris:
![pastedgraphic-12](https://cloud.githubusercontent.com/assets/12385914/7623594/247bfa80-f991-11e4-8bb4-3b400ff06152.png)

versus Linux:
![pastedgraphic-13](https://cloud.githubusercontent.com/assets/12385914/7623598/335f4c8c-f991-11e4-9dbf-f1cd8f6db1c0.png)

**Comment by zevv** [comment] 2015-05-14 07:03
* On 2015-05-14 01:59:20 +0200, stuartthebruce wrote:
 
> However, Linux is not able to read the Solaris file,

Could you index the 'test' directory from the duc git repo on solaris
and send me the stderr output and the resulting database file:

    ./duc index --debug -Hv test 2> test.out

> Perhaps related to the different gui graphs the ui command the Solaris
> system down not show the sort the entries by size, whereas the Linux
> build does, i.e.,

So there's an issue with sorting on Solaris, which is probably also
causing the malformed graphs. I suspect where the problem might be.

Please pull the portable-db to latest and try to generate graphs on
solaris.

-- 
:wq
^X^Cy^K^X^C^C^C^C

**Comment by zevv** [comment] 2015-05-14 07:58
* On 2015-05-14 09:03:04 +0200, Ico Doornekamp wrote:
 
> * On 2015-05-14 01:59:20 +0200, stuartthebruce wrote:
>  
> > However, Linux is not able to read the Solaris file,
> 
> Could you index the 'test' directory from the duc git repo on solaris
> and send me the stderr output and the resulting database file:
> 
>     ./duc index --debug -Hv test 2> test.out

Sorry, forgot to say: the test directory is not included in the git
repo, but generated by the ./test.sh script. Not sure if you can run
this script on solaris because it requires valgrind. Please find
attached a tgz with the test tree.

-- 
:wq
^X^Cy^K^X^C^C^C^C

**Comment by stuartthebruce** [comment] 2015-05-14 22:06
> On May 14, 2015, at 12:58 AM, Ico Doornekamp <notifications@github.com <mailto:notifications@github.com>> wrote:
> 
> * On 2015-05-14 09:03:04 +0200, Ico Doornekamp wrote:
> 
> > * On 2015-05-14 01:59:20 +0200, stuartthebruce wrote:
> > 
> > > However, Linux is not able to read the Solaris file,
> > 
> > Could you index the 'test' directory from the duc git repo on solaris
> > and send me the stderr output and the resulting database file:
> > 
> > ./duc index --debug -Hv test 2> test.out
> 
> Sorry, forgot to say: the test directory is not included in the git
> repo, but generated by the ./test.sh script. Not sure if you can run
> this script on solaris because it requires valgrind. Please find
> attached a tgz with the test tree.

FWIW, my Scientific Linux 6 machine also has a problem with test.sh, i.e.,

# valgrind --version
valgrind-3.6.0

# ./test.sh
valgrind error
valgrind: Bad option: --show-leak-kinds=all
valgrind: Use --help for more information or consult the user manual.

and if I remove that option I get the following in the current
duc-portable-db branch,

[root@ldas-pcdev2 duc]# ./test.sh
valgrind error
location should be "...", or should start with "fun:" or "obj:"
==8516== FATAL: in suppressions file "valgrind-suppressions" near line 37:
==8516==    location should be "...", or should start with "fun:" or "obj:"
==8516== exiting now.

Thanks.

--
Stuart Anderson  anderson@ligo.caltech.edu <mailto:anderson@ligo.caltech.edu>
http://www.ligo.caltech.edu/~anderson <http://www.ligo.caltech.edu/~anderson>

**Comment by zevv** [comment] 2015-05-14 22:09
* On 2015-05-15 00:06:47 +0200, stuartthebruce wrote:
 
> # valgrind --version
> valgrind-3.6.0

Mine is 3.10.0, so that explains. I'll have to cleanup the test script
to make it work for others as well then.

-- 
:wq
^X^Cy^K^X^C^C^C^C

**Comment by stuartthebruce** [comment] 2015-05-14 22:35
> On May 14, 2015, at 12:03 AM, Ico Doornekamp <notifications@github.com> wrote:
> 
> * On 2015-05-14 01:59:20 +0200, stuartthebruce wrote:
> 
> > However, Linux is not able to read the Solaris file,
> 
> Could you index the 'test' directory from the duc git repo on solaris
> and send me the stderr output and the resulting database file:
> 
> ./duc index —debug -Hv test 2> test.out

This results in,

# tail -1 test.out
Indexed 39 files and 27 directories, (106.6KB apparent, 60.0KB actual) in 0.005145 secs.

I will see if I can figure out how to upload the full test.out file.

> 
> > Perhaps related to the different gui graphs the ui command the Solaris
> > system down not show the sort the entries by size, whereas the Linux
> > build does, i.e.,
> 
> So there's an issue with sorting on Solaris, which is probably also
> causing the malformed graphs. I suspect where the problem might be.
> 
> Please pull the portable-db to latest and try to generate graphs on
> solaris.

Running info on a Linux box against a Solaris generated database file
still comes back empty, i.e.,

# ./duc info -d solaris.db
Date       Time       Files    Dirs    Size Path
#

The graph and gui commands run on Linux against the Solaris generated
test database file now results in, “Requested path not found”.


Running ui on the Solaris machine against “index test” generated on
the Solaris machine results in the following output,

  /root/duc/test                                                                                         
  29.5K strange/                                  [====================================================] 
  16.5K tree/                                     [=============================                       ]
   7.5K utf-8/                                    [=============                                       ]
   3.0K hard-link/                                [=====                                               ]
   2.0K sparse/                                   [===                 

Running graph on Solaris against the Solaris generated
test database file results in a reasonable image that
I will upload separately.

Thanks

--
Stuart Anderson  anderson@ligo.caltech.edu
http://www.ligo.caltech.edu/~anderson

**Comment by stuartthebruce** [comment] 2015-05-14 22:46
Here is the ui output on Solaris for a scan of the / filesystem,
 
 /                                                                                                      
  94.6M boot/                                     [==                                                  ] 
  90.8M etc/                                      [==                                                  ]
    512 bin>                                      [                                                    ]
   1.9G usr/                                      [====================================================]
   2.5K media/                                    [                                                    ]
  19.3M root/                                     [                                                    ]
    512 ldcg_admin>                               [                                                    ]
  40.7M lib/                                      [=                                                   ]
    512 ldcg>                                     [                                                    ]
   9.0K pkgrepo/                                  [                                                    ]
    512 reconfigure                               [                                                    ]
  35.4M opt/                                      [                                                    ]
  60.8M kernel/                                   [=                                                   ]
 133.4M platform/                                 [===                                                 ]
   3.0K mnt/                                      [                                                    ]
   3.0K system/                                   [                                                    ]
   1.5K cdrom/                                    [                                                    ]
   1.5K home/                                     [                                                    ]
   1.5K nfs4/                                     [                                                    ]
    512 ldas_usr>                                 [                                                    ]
    512 sbin>                                     [                                                    ]

Here is the duc graph plot generated on Solaris machine for the test/ directory.

![pastedgraphic-2](https://cloud.githubusercontent.com/assets/12385914/7643630/15494dc8-fa50-11e4-9148-ae47b2e670a9.png)

**Comment by stuartthebruce** [comment] 2015-05-15 02:56
I couldn't figure out how to attach a the test.out file generated on a Solaris machine so here is a cut-n-paste,

MBP:~> cat test.out
Writing to database "/root/.duc.db"
>> /root/duc/test
>> tree
    100 512 one
>> sub3
    5000 512 india
    4000 512 juliet
<< sub3 actual:9004 apparent:2560
>> sub4
    5000 512 november
    1000 512 kilo
    3000 512 mike
    2000 512 lima
<< sub4 actual:11006 apparent:3584
    100 512 three
    100 512 two
    100 512 four
>> sub1
    100 512 alpha
    1000 512 charlie
    1000 512 bravo
    10000 512 delta
<< sub1 actual:12106 apparent:3584
>> sub2
    10000 512 hotel
    100 512 echo
    1000 512 foxtrot
    1000 512 golf
<< sub2 actual:12106 apparent:3584
<< tree actual:44632 apparent:16896
>> utf-8
>> оживлённым
    100 512 foo
<< оживлённым actual:103 apparent:2048
>> ♜♞♝♛♚♝♞♜
    100 512 foo
<< ♜♞♝♛♚♝♞♜ actual:103 apparent:2048
>> 有朋自遠方來
    100 512 foo
<< 有朋自遠方來 actual:103 apparent:2048
<< utf-8 actual:314 apparent:7680
>> strange
>> single-quote-'-dir
    100 512 file
<< single-quote-'-dir actual:103 apparent:2048
>> ampersand-&-dir
    100 512 file
<< ampersand-&-dir actual:103 apparent:2048
>> more-then->-dir
    100 512 file
<< more-then->-dir actual:103 apparent:2048
>> cgi-space-%20-dir
    100 512 file
<< cgi-space-%20-dir actual:103 apparent:2048
>> control-a--dir
    100 512 file
<< control-a--dir actual:103 apparent:2048
>> carriage-return-
-dir
    100 512 file
<< carriage-return-
-dir actual:103 apparent:2048
>> backslash-\-dir
    100 512 file
<< backslash-\-dir actual:103 apparent:2048
>> space- -dir
    100 512 file
<< space- -dir actual:103 apparent:2048
>> less-then-<-dir
    100 512 file
<< less-then-<-dir actual:103 apparent:2048
>> tab-	-dir
    100 512 file
<< tab-	-dir actual:103 apparent:2048
>> escape-ir
    100 512 file
<< escape-ir actual:103 apparent:2048
>> double-quote-"-dir
    100 512 file
<< double-quote-"-dir actual:103 apparent:2048
-direwline-
    100 512 file
-dir actual:103 apparent:2048
>> question-mark-?-dir
    100 512 file
<< question-mark-?-dir actual:103 apparent:2048
<< strange actual:1458 apparent:30208
>> sparse
    32769 512 first
<< sparse actual:32772 apparent:2048
>> hard-link
    10000 512 three
    10000 512 two
    10000 512 one
<< hard-link actual:30005 apparent:3072
<< /root/duc/test actual:109188 apparent:61440
Indexed 39 files and 27 directories, (106.6KB apparent, 60.0KB actual) in 0.005145 secs.

**Comment by stuartthebruce** [comment] 2015-05-15 03:26
I wanted to thank you for helping to get this working on Solaris. I just ran a benchmark where running duc index  on a Soalris file server for a large filesystem takes 3 hours compared to just over 24 hours when run on a Linux NFS client.

In case it was missed in the earlier responses, today's builds against the duc-portable-db branch breaks the previous ability to generate a database file on solaris that can be graphed on a linux machine. The current code when run on Linux against a solaris database file generates the message, "Requested path not found".

Thanks.

**Comment by zevv** [comment] 2015-05-15 05:14
* On 2015-05-15 05:26:02 +0200, stuartthebruce wrote:
 
> I wanted to thank you for helping to get this working on Solaris. 

Your welcome. Thanks for the test results, I'm a bit confused however
about the results. To speed up the debugging process I'll try to setup a
solaris (openindiana) machine here so I can reproduce and test locally.

-- 
:wq
^X^Cy^K^X^C^C^C^C

**Comment by zevv** [comment] 2015-05-15 06:07
By the way, your Solaris-generated graph looks just fine now, so the issue was in the quicksort()  comparision function which I overoptimized for performance: ok on linux but broken on solaris.

So the last step would be fixing the portability between OS's, which I should be able to do with my local opensolaris install later this week.

**Comment by stuartthebruce** [comment] 2015-05-15 14:34
> On May 15, 2015, at 1:07 AM, Ico Doornekamp <notifications@github.com> wrote:
> 
> By the way, your Solaris-generated graph looks just fine now, so the issue was in the quicksort() comparision function which I overoptimized for performance: ok on linux but broken on solaris.
> 
I am not sure. I agree the solaris graph of the test/ directory looks reasonable, however, a solaris graph of a / filesystem still looks wrong to me.

> So the last step would be fixing the portability between OS’s, which I should be able to do with my local opensolaris install later this week.


That would be great.

Thanks.

--
Stuart Anderson  anderson@ligo.caltech.edu
http://www.ligo.caltech.edu/~anderson

**Comment by zevv** [comment] 2015-05-15 19:49
After an evening of fighting a conflict between kvm/qemu and solaris and learning solaris package basic I have a working setup. Duc builds with the basic solaris packages and OpenCSW tokyocabinet just like you described, and I get proper results indexing and generating graphs on Solaris.

You said the graph of a / 'looks wrong' to you; can you describe your problem in more detail?

**Comment by l8gravely** [comment] 2015-05-15 20:57
Guys,

I can do test builds on Solaris 5.8,9,10 Sparc, and 5.10 Intel next
week.  Though getting Tokyocabinet and other pre-reqs installed might
be a hassle...

So that should inspire me to get the indexing only part working in
configure.ac as well, so that we can index from Solaris and display on
linux.

Been flat out the past few weeks... barely any time to look at this
proeprly.

John

**Comment by stuartthebruce** [comment] 2015-05-16 03:42
On May 15, 2015, at 2:49 PM, Ico Doornekamp <notifications@github.com> wrote:
> 
> After an evening of fighting a conflict between kvm/qemu and solaris and learning solaris package basic I have a working setup. Duc builds with the basic solaris packages and OpenCSW tokyocabinet just like you described, and I get proper results indexing and generating graphs on Solaris.
> 
Which code branch are you running?

If you copy the database file to Linux are you able to run info and generate graphs?

> You said the graph of a / 'looks wrong' to you; can you describe your problem in more detail?
> 
With the latest code I was no longer to generate a graph from a Solaris generated database file on a Linux machine at all, and the Solaris generated image of an index of / showed only a few slices going around the 360deg plot being shows (similar to the earlier images in this thread.

However, if you confirm which git branch is working for you I will try again.

Thanks.

--
Stuart Anderson  anderson@ligo.caltech.edu
http://www.ligo.caltech.edu/~anderson

**Comment by stuartthebruce** [comment] 2015-05-16 03:45
> On May 15, 2015, at 3:57 PM, John <notifications@github.com> wrote:
> 
> 
> Guys,
> 
> I can do test builds on Solaris 5.8,9,10 Sparc, and 5.10 Intel next
> week. Though getting Tokyocabinet and other pre-reqs installed might
> be a hassle…

FWIW, I am personally only interested in Solaris 11.2 on Intel.
That version has enough open source tools bundled that I believe
all you need to install is Tokyocabinet, which is available via
OpenCSW. However, older versions of Solaris may require you install
additional packages needed by duc.

> 
> So that should inspire me to get the indexing only part working in
> configure.ac as well, so that we can index from Solaris and display on
> linux.

That would be great, and is my primary use case, i.e., index on Solaris
and display (primarily via cgi) on Linux.

Thanks.

--
Stuart Anderson  anderson@ligo.caltech.edu
http://www.ligo.caltech.edu/~anderson

**Comment by zevv** [comment] 2015-05-16 05:19
* On 2015-05-16 05:42:06 +0200, stuartthebruce wrote:
 
> On May 15, 2015, at 2:49 PM, Ico Doornekamp <notifications@github.com>
> wrote:

> Which code branch are you running?

SunOS solaris 5.11 11.2 i86pc i386 i86pc

> If you copy the database file to Linux are you able to run info and
> generate graphs?

I can confirm this does *not* work. However, the problem seems to be at
the tokyocabinet-level: I am not able to open or query the
solaris-generated-database at linux, neither with Duc or with tcbmgr
(the tokyocabinet cmdline tool)

> With the latest code I was no longer to generate a graph from a
> Solaris generated database file on a Linux machine at all, and the
> Solaris generated image of an index of / showed only a few slices
> going around the 360deg plot being shows (similar to the earlier
> images in this thread.

Did you test this before or after I fixed the sorting issue in commit
f047738e597f8a840d6ef4bdb232702cc30e17bf?

> However, if you confirm which git branch is working for you I will try
> again.

Please do, thank you

-- 
:wq
^X^Cy^K^X^C^C^C^C

**Comment by zevv** [comment] 2015-05-16 07:26
@stuartthebruce: a summary of the current situation. The portable-db branch will be obsoleted, new fixes are going into master. Master is now functional for me on solaris without issues.

- Drawing graphs was broken on solaris because of the qsort helper function. This is fixed in master.

- Autoconf scripts now detects ncurses/ncurses.h, so no source modifications should be necessary for solaris.

- Sqlite3 is available as package from sun, so you should be able to run Duc without requiring opencw by using --with-db-backend=sqlite3

- It seems that tokyocabinet databases are not guaranteed to be portable between platforms, so at this time it is no use to keep the contents portable. I'm planning to add export/import functionality one day, which could be used to transfer databases between platforms

**Comment by stuartthebruce** [comment] 2015-05-18 00:10
I thought there was a version on the portable-db branch that had the following md5sum value,
70d4cb3cbb95ecbf2c3ae1117e5a9429 src/libduc/index.c
that was able to build a tokyocabinet index on Solaris and display with gui on Linux, however, I have been unable to find that MD5 value in git nor find a build that displays a solaris tokyocabinet database file on linux.

I am also unable to get the current head (a072187246d005c1e1ef696b7328e2c4d598a7da) when configured to use sqlite3 to build an index on Solaris that can be graphed on Linux (the info command also comes up blank). Is that to be expected?

Thanks.

**Comment by zevv** [comment] 2015-05-18 07:41
We're trying to accomplish several goals, let's split them into separate
issues to avoid confusion:

1. Make duc function properly on solaris.
2. Find a way to share databases between platforms

Let's keep this issue for #1, I'll create a new one in github for #2.

So, what's the status of the master branch on Solaris for you?

-- 
:wq
^X^Cy^K^X^C^C^C^C

**Comment by zevv** [comment] 2015-05-18 19:18
I just made one more bugfix in master for solaris, there was a type mismatch in the graph code causing strange looking graphs because relative sizes were calculated wrong. Master is now fully functional for me on solaris.

@stuartthebruce: if we get master properly going on solaris for you, I have a patch ready which should provide portable databases between solaris and linux if you choose a portable db backed (sqlite3)

**Comment by stuartthebruce** [comment] 2015-05-19 00:41
> On May 18, 2015, at 12:41 AM, Ico Doornekamp <notifications@github.com> wrote:
> 
> We're trying to accomplish several goals, let's split them into separate
> issues to avoid confusion:
> 
> 1. Make duc function properly on solaris.
> 2. Find a way to share databases between platforms
> 
> Let's keep this issue for #1, I'll create a new one in github for #2.
> 
> So, what’s the status of the master branch on Solaris for you?

issue #1 is looking good for me on two systems. On another I have a font problem, but I don’t think it has anything to do with duc,
Pango-WARNING **: failed to choose a font, expect ugly output. engine-type=‘PangoRenderFc', script='latin'


Thanks.

--
Stuart Anderson  anderson@ligo.caltech.edu
http://www.ligo.caltech.edu/~anderson

**Comment by stuartthebruce** [comment] 2015-05-19 00:46
> On May 18, 2015, at 12:18 PM, Ico Doornekamp <notifications@github.com> wrote:
> 
> I just made one more bugfix in master for solaris, there was a type mismatch in the graph code causing strange looking graphs because relative sizes were calculated wrong. Master is now fully functional for me on solaris.
> 
Looks good to me as well.
> @stuartthebruce <https://github.com/stuartthebruce>: if we get master properly going on solaris for you, I have a patch ready which should provide portable databases between solaris and linux if you choose a portable db backed (sqlite3)
> 
I will give that a try when it is available, though I really like the much smaller tokyocabinet.

Perhaps there is some compiler flag(s) I can use to get the limited portability with tokyocabinet that I want between Linux and Solaris on x86_64. Given the same sizeof(int), sizeof(long) and endianness do you have any idea what piece of the puzzle is not portable? 

Thanks.

--
Stuart Anderson  anderson@ligo.caltech.edu
http://www.ligo.caltech.edu/~anderson

**Comment by zevv** [comment] 2015-05-19 05:44
Ok, assuming all is well on the solaris platform, closing this issue now.

**Closed by zevv** 2015-05-19 05:44 UTC
