### ISSUE TITLE
duc indexing put stress on NAS

### ISSUE THREAD

**Issue by robina80** [zevv/duc#203] opened 2018-10-04 10:46 UTC
hi all,

i have made a script for duc and i have made it run an index every 4 hours (takes roughtly an hour to index the whole NAS which is 1.2P) when duc indexes my NAS box does this put stress on my NAS ie does it make my NAS box slower as duc is indexing it every 4 hours?

cheers,
rob

**Comment by zevv** [comment] 2018-10-04 11:18
(Duplicate of #175)

Quoting robina80 (2018-10-04 12:46:26)

> i have made a script for duc and i have made it run an index every 4
> hours (takes roughtly an hour to index the whole NAS which is 1.2P)
> when duc indexes my NAS box does this put stress on my NAS ie does it
> make my NAS box slower as duc is indexing it every 4 hours?

You bet it will - traversing the filesystem is still a pretty heavy task
these days. (which is exactly why Duc exists: if it was fast, there was
no need to create an index because you could just ask the file system
instead of putting the numbers in a datbase first)

To prevent Duc from taking too much resources on your machine, you can
run it using 'nice' and 'ionice':

   nice -20 ionice -c 3 duc index ...

This gives the lowest CPU and I/O priorities to Duc, making sure other
processes come first.

I have just added a section to the FAQ explaining the above.

--
:wq
^X^Cy^K^X^C^C^C^C

**Comment by robina80** [comment] 2018-10-04 11:47
is this the right syntax - 

time /usr/local/bin/nice -20 ionice -c 3 duc index -d /pie/.duc.db -p /shares/

**Comment by robina80** [comment] 2018-10-04 12:07
when i run this command by itself it works - 

nice -20 ionice -c 3 duc index -d /duc2/.duc.db -p /shares/cha-work/

but this doesnt - 

/usr/local/bin/duc nice -20 ionice -c 3 duc index -d /duc2/.duc.db -p /shares/cha-work/

basically im running this in a bash script so i need the full path to the duc so it runs in the enviroment

**Comment by zevv** [comment] 2018-10-04 12:18
Quoting robina80 (2018-10-04 14:07:07)
> when i run this command by itself it works - 
> 
> nice -20 ionice -c 3 duc index -d /duc2/.duc.db -p /shares/cha-work/
> 
> but this doesnt - 
> 
> /usr/local/bin/duc nice -20 ionice -c 3 duc index -d /duc2/.duc.db -p /shares/cha-work/

You are trying to pass the 'nice -20 ...' string to the duc binary. I
guess you mean:

```
nice -20 ionice -c 3 /usr/local/bin/duc index -d /duc2/.duc.db -p /shares/cha-work/
```


--
:wq
^X^Cy^K^X^C^C^C^C

**Closed** 2018-10-04 13:11 UTC
