### ISSUE TITLE
indexer requires --verbose

### ISSUE THREAD

**Issue by d33psky** [zevv/duc#55] opened 2015-01-21 14:39 UTC
Test VM running Ubuntu 12.04.3 LTS , https://github.com/zevv/duc/archive/master.zip of 20150121

Indexer errors out on : 
duc index --one-file-system /
Required index PATH missing.

When adding --verbose it works : 
duc index --verbose --one-file-system / 
Writing to database "/root/.duc.db"
...

Indexer should not require --verbose

**Comment by zevv** [comment] 2015-01-21 15:16
Hi,

Thanks for the report. The problem is in the handling of the longopt.
Using '-x' instead of '--one-file-system' works as expected.

Fixed in 252079e

* On 2015-01-21 15:39:53 +0100, d33psky wrote:
 
> Test VM running Ubuntu 12.04.3 LTS , https://github.com/zevv/duc/archive/master.zip of 20150121
> 
> Indexer errors out on : 
> duc index --one-file-system /
> Required index PATH missing.
> 
> When adding --verbose it works : 
> duc index --verbose --one-file-system / 
> Writing to database "/root/.duc.db"
> ...
> 
> Indexer should not require --verbose
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/zevv/duc/issues/55

-- 
:wq
^X^Cy^K^X^C^C^C^C

**Closed** 2015-01-21 15:17 UTC

**Comment by d33psky** [comment] 2015-01-21 15:34
Thanks for quick update. I can confirm that
duc index -x /
works as expected.
