### ISSUE TITLE
Query multiple databases which indexed a different directory without specifying -d databasefilename on the commandline

### ISSUE THREAD

**Issue by ghuls** [zevv/duc#33] opened 2014-07-30 17:07 UTC
I wrote a bash function to allow querying multiple databases (which indexed a different directory (actually fileserver)) to avoid the need to specify -d databasename on the command line.

It would be nice if duc would support something like this in the future by default.

```
Usage:
  # This will use the '/media/srv-01/duc/db/srv-01.duc.db' database.
  duce ls /media/srv-01

  # This will use the '/media/srv-03/duc/db/srv-03.duc.db' database.
  duce ls /media/srv-03/some/path

  # This will use the '/media/srv-03/duc/db/srv-03-more-often.duc.db' database.
  duce ls /media/srv-03/path/that/gets/indexed/more/often/something
```

Add this script to your .bashrc:
```bash
# Enhanced duc function (a better name is welcome).
duce () {
    # Link indexed paths with database filenames.
    local -A pathname_to_db_array;

    # START: Adapt the paths to your configuration.
    pathname_to_db_array['/media/srv-01']='/media/srv-01/duc/db/srv-01.duc.db';
    pathname_to_db_array['/media/srv-02']='/media/srv-02/duc/db/srv-02.duc.db';
    pathname_to_db_array['/media/srv-03']='/media/srv-03/duc/db/srv-03.duc.db';
    pathname_to_db_array['/media/srv-03/path/that/gets/indexed/more/often']='/media/srv-03/duc/db/srv-03-more-often.duc.db';
    # END: Adapt the paths to your configuration.

    if [ ${#@} -ge 1 ] ; then
        local command="${1}";
        
        local -i parse_path=0;
        
        case "${command}" in
            help)  duc ${@};
                   return $?;;
            info)  duc ${@};
                   return $?;;
            index) duc ${@};
                   return $?;;
            gui)   parse_path=1;;
            ls)    parse_path=1;;
            graph) parse_path=1;;
            xml)   parse_path=1;;
            *)     duc help;
                   return $?;
        esac
        
        if [ ${parse_path} -eq 1 ] ; then
            local arg='';
            local path='';
            local absolute_path='';
            local pathname_key='';
            local suffix_path='';
            local -i length_suffix_path=999999999;
            local db_filename='';

            for arg in ${@:2} ; do
                # Last variable can be the path, so save it.
                path=${arg};
            done;
            
            if [ ! -e "${path}" ] ; then
                # If the last variable is not a path, or does not exist,
                # use the current working directory.
                path="${PWD}";
            fi
            
            # Get absolute path.
            absolute_path=$(realpath -s "${path}");
            
            # Check if the absolute path starts with one of the paths used as keys in the pathname_to_db_array.
            for pathname_key in "${!pathname_to_db_array[@]}" ; do
                suffix_path="${absolute_path#"${pathname_key}"}";
                
                if [ "${suffix_path}" != "${absolute_path}" ] ; then
                    # Take the key value of pathname_to_db array that has the longest match with the absolute path name.
                    if [ ${length_suffix_path} -gt ${#suffix_path} ] ; then
                        length_suffix_path=${#suffix_path};
                        db_filename="${pathname_to_db_array["${pathname_key}"]}";
                    fi
                fi
            done

            if [ -z "${db_filename}" ] ; then
                # If the database filename was empty, the absolute path did not start with any of the pathnames in pathname_to_db_array. 
                duc ${@};
                return $?;
            elif [ -f "${db_filename}" ] ; then
                # The best database for the provided path was found.
                duc ${command} -d "${db_filename}" "${@:2}";
                return $?;
            else
                printf 'Error: database filename "%s" does not exist.\n' "${db_filename}" > /dev/stderr;
                return 1;
            fi
        fi
    else
        # Display help when no arguments are given.
        duc help;
        return $?;
    fi
}
```

**Comment by zevv** [comment] 2015-04-23 12:24
I'm closing this issue for now, and marking it duplicate of #8. Not really the same, but both related to working with multiple databases.

**Closed by zevv** 2015-04-23 12:24 UTC
Labels: duplicate
