### ISSUE TITLE
count output in cgi mode

### ISSUE THREAD

**Issue by stuartthebruce** [zevv/duc#127] opened 2016-03-03 22:45 UTC
The new --count option is awesome!

With version 1.4.0 in cgi mode the Size output when in --count mode is rather strange, e.g., "7.2E" is output in the following example (though I have also seen "0".

# env SCRIPT_NAME= GATEWAY_INTERFACE= duc cgi -d home2.duc --count | tail -20
<div id=main>
<div id=index> <table>
  <tr>
   <th>Path</th>
   <th>Size</th>
   <th>Files</th>
   <th>Directories</th>
   <th>Date</th>
   <th>Time</th>
  </tr>
  <tr>
   <td><a href="?cmd=index&path=/home2">/home2</a></td>
   <td>7.2E</td>
   <td>200359302</td>
   <td>8920950</td>
   <td>2016-03-03</td>
   <td>00:30:04</td>
  </tr>
 </table>
</div>

If there isn't a better value to display then presumably the same value shown when not in --count mode would be appropriate. In this case that would be "75.1T", i.e.,

# env SCRIPT_NAME= GATEWAY_INTERFACE= duc cgi -d home1.duc | tail -20
<div id=main>
<div id=index> <table>
  <tr>
   <th>Path</th>
   <th>Size</th>
   <th>Files</th>
   <th>Directories</th>
   <th>Date</th>
   <th>Time</th>
  </tr>
  <tr>
   <td><a href="?cmd=index&path=/home1">/home1</a></td>
   <td>75.1T</td>
   <td>206072917</td>
   <td>7637466</td>
   <td>2016-03-03</td>
   <td>00:30:03</td>
  </tr>
 </table>
</div>

**Comment by stuartthebruce** [comment] 2016-03-03 22:47
Now that I look closer, why are the Files and Directories values different depending on whether --count is specified or not?

**Comment by stuartthebruce** [comment] 2016-03-03 22:50
Ignore the previous comment regarding Files/Directories values as I was comparing the output from two different databases (home1 vs home2).

**Comment by zevv** [comment] 2016-03-05 08:10
I'm not able to reproduce the strange number you see there (7.2E), and at the moment I have no clue where this is coming from.

About the 'size' field in the table:

short answer: agree, fixed in 6a1a8da.

long answer: There' s a small issue with options which are not quite orthogonal: Duc now keeps track of 3 different sizes for each entry: actual size, apparent size and child count. The options --count and --apparent, which allow for 4 permutations, now map onto these 3 size types. There's one underlying mechanism that formats the file size to show to the user, depending on these flags, and it's not always clear where we should or should not use the requested format. Like your issue: if --count is given, the index list should probably still show size instead of count.

**Closed by zevv** 2016-03-05 08:10 UTC

**Comment by stuartthebruce** [comment] 2016-03-07 04:00
> On Mar 5, 2016, at 12:10 AM, Ico Doornekamp <notifications@github.com> wrote:
> 
> I'm not able to reproduce the strange number you see there (7.2E), and at the moment I have no clue where this is coming from.
> 
Hopefully that was the result of displaying an uninitialized value that goes away now that you are displaying the size in —count mode, e.g.,

env SCRIPT_NAME= GATEWAY_INTERFACE= ./duc cgi --count -d /var/www/html/diskusage/ducdb/filesystem/home1.duc | tail
  <tr>
   <td><a href="?cmd=index&path=/home1">/home1</a></td>
   <td>75.5T</td>
   <td>206558035</td>
   <td>7689796</td>
   <td>2016-03-06</td>
   <td>00:30:021</td>
  </tr>
 </table>
</div>

However, please note the extra digit for the seconds field in the last <td> entry. Note, in the case of 1.4.0 the output is “<td>00:30:02</td>”.

Presumably either the extra digit should be removed or a decimal point added?

> About the 'size' field in the table:
> 
> short answer: agree, fixed in 6a1a8da <https://github.com/zevv/duc/commit/6a1a8da77943194daa997cca8d46e9381641a4fd>.
> 

Thanks. Are you planning on spinning a new release soon?

--
Stuart Anderson  anderson@ligo.caltech.edu
http://www.ligo.caltech.edu/~anderson
