### ISSUE TITLE
proc gets indexed while --one-file-system was given

### ISSUE THREAD

**Issue by d33psky** [zevv/duc#54] opened 2015-01-21 14:36 UTC
Test VM running Ubuntu 12.04.3 LTS , https://github.com/zevv/duc/archive/master.zip of 20150121

created index with : duc index --verbose --one-file-system /

duc ls / -Fcg
shows proc (with 128.0T) as first item ;-)

The indexer should skip proc, especially with --one-file-system

**Comment by zevv** [comment] 2015-01-21 15:17
Duplicate of #55

**Closed by zevv** 2015-01-21 15:17 UTC
